### ISSUE TITLE
Telephone Question

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#10]
- [ ] Implement Logic Mask for Cambodia’s mobiles
- [x] Implement Layout
- [x] Finalize survey button

**Comment by adrianq** [comment]
Mask telephone library: https://github.com/googlei18n/libphonenumber

**Comment by ivanarrizabalaga** [comment]
@adrianq Using PhoneNumberFormattingTextWatcher the number is automatically formatted according to the locale of the device.

This might be sufficient but I'm not sure.

**Comment by adrianq** [comment]
@ivanarrizabalaga I think so! I will confirm it with the client but I think it is more than enough!
