### ISSUE TITLE
Data seem to be attached always to the same survey

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1006]
Looks also like being related to #990 feature

**Comment by ifoche** [comment]
When you fill in a survey, if you look at the details shown in the dashboard, it appears like all the data for different surveys was attached to the same one, or at least duplicated several times. Please look at the following image:

![device-2017-03-29-093738](https://cloud.githubusercontent.com/assets/10931645/24443579/8153b1dc-1463-11e7-8935-836f3ab13613.png)

It could also be related to #990 so please start working from bug-creating_second_survey_go_to_last_question branch, that fix that problem, just in case this issue is already solved there

**Comment by idelcano** [comment]
I think this is solved in #779

**Comment by ifoche** [comment]
ok, as we've just talked, we will wait for all PRs to be merged and test it again to give the final approval.

**Comment by idelcano** [comment]
@ifoche this bug isn't in the development branch after merge of #779 . I will close this issue

**Comment by idelcano** [comment]
Solved in #781
