### ISSUE TITLE
Review swype (delete) on dashboard

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#104]

**Comment by idelcano** [comment]
I found the problem: The method delete is not working in the surveys.

**Comment by idelcano** [comment]
I found the solution with the deletion of surveys. But I found another problem , surveys are always stored as full ( never in progress) . I 'm looking for where it occurs .

But I found a very annoying problem
If the application is closed, the application continues to send requests, and sometimes the user dialog is displayed . I'll fix this problem in this issue branch.
