### ISSUE TITLE
Review AndroidManifest permissions

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/pictureapp#106]
Analice all the user-permissions.

These permission are important:
READ_CONTACTS, READ_PROFILE, GET_ACCOUNTS, USE_CREDENTIALS
And 
READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE

**Comment by adrianq** [comment]
@idelcano  Please, if possible, try to have a look at this card first thing tomorrow so we can tell something to the client asap.

**Comment by idelcano** [comment]
ok!

**Comment by idelcano** [comment]
The application works correctly without these user-permissions , including crashlytics . On its website says nothing about user permissions .
Here is the branch
[branch](https://waffle.io/EyeSeeTea/pictureapp/cards/5626664f051b60cb000a92cc)

Removed user-permissions:
USE_CREDENTIALS -> To retrieve the account name (email) as part of sign-in
GET_ACCOUNTS -> To auto-complete the email text field in the login form with the user's emails
READ_PROFILE->Constants for the user's profile data, which is represented as a single contact on the device that represents the user. The user Querying for profile data requires android.permission.READ_PROFILE permission.
READ_CONTACTS->Allows an application to read the user's contacts data. 
READ_EXTERNAL_STORAGE-> Allows an application to read from external storage

Needed to profile with Debug class:
android.permission.WRITE_EXTERNAL_STORAGE->Allows an application to write from external storage

**Comment by adrianq** [comment]
So I  guess from your commit that we don't need any permission except location, internet and phone state, right?

**Comment by idelcano** [comment]
@adrianq yes, i checked all the application. 
crashlytics:
I caused an exception and it was reported correctly on crashlytics .
And i not found nothing in their documentation on these permits

WRITE EXTERNAL STORAGE:
I do not know how works android.debug operation, but i know it needs WRITE EXTERNAL STORAGE permissison, the android.debug is not used at this moment.
The application works and does not suffer any crash.

I only have one dude:
That if I 'm not seeing the surveys in [event_capture](https://malariacare.psi.org/dhis-web-event-capture/index.html#/)
But this happens in all versions
But seem fine pulled
[last_event](https://malariacare.psi.org/api/events/Rga5VjSN30d)

**Comment by adrianq** [comment]
Great! Thanks! I will merge it now. @ifoche Finally it looks like we don't need [all these libraries](https://github.com/EyeSeeTea/pictureapp/commit/9eb162932c289ea50b810dbca2eee010554c54a5). Just in case you want to remove them from malariapp as well.
