### ISSUE TITLE
Create Survey converter for json format

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1084]
Surveys won't be sent using the SDK as typically we do with DHIS2, because we will send the surveys to a Web Service. This Web Service (not ready yet) will have an API that accept the following API requests...
{
  "version": "1.0",
  "referrals": [
    {
      "UID": "dawbLaHPq4E",
      "values": [
        {
          "firstName": "Nacho",
          "lastName": "Foche",
          “telephone”: “0025512345678”
        }
{
      "UID": "asdf3rwsdf",
      "values": [
        {
          "firstName": "Nacho",
          "lastName": "Foche",
          “telephone”: “0025512345678”
        }
      ]
    }
  ]
}

and the replies will have the following format
{
  "version":"1.0"
  "referrals": [
    {
      "UID": "dawbLaHPq4E",
      "status": "Accepted",
      "message": "Data was accepted."
    },
    {
      "UID": "asdf3rwsdf",
      "status": "Rejected",
      "message": "Reason for not accepting."
    },
    {
      "UID": "DawbL098q4E",
      "status": "Warning",
      "message": "Something important for you to know."
    }
  ]
}

**Comment by ifoche** [comment]
As per @manuelplazaspalacio suggestion, we changed it into this other way:
{
  "version": "1.0",
  "referrals": [
    {
      "UID": "dawbLaHPq4E",
      "values": [
        {
          "name": "firstName",
          "value": "Nacho"
        },
        {
          "name": "lastName",
          "value": "Foche"
        },
        {
          "name": "telephone",
          "value": "0025512345678"
        }
      ]
    }
  ]
}

having an array of value objects

**Comment by ifoche** [comment]
we have response from WS side, and it looks like they want a format like this one:
{
  "version": "1.0",
  "actions": [
    {
       "type": "referral",
       "actionId": "asdfasdf",
       "orgUnitId": "asdfasd",
       "attributeValues": [
         {  "name": "firstName", "id": "ffdisldf", "value": "James" },     // <-- "name" would not be that important at this case..
         {  "name": "lastName", "id": "idfdisldf", "value": "Tester" }
        ]
    }
   ]
}

**Comment by manuelplazaspalacio** [comment]
Solved in https://github.com/EyeSeeTea/pictureapp/issues/1151
