### ISSUE TITLE
answeredRatio.isCompleted() returns false in a negative test

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/pictureapp#110]
if you send a survey with negative test, the SurveyAnsweredRatio.iscompleted() returns false, and the survey status changes to in progress and will be deleted.

[Link of a problem](https://github.com/EyeSeeTea/pictureapp/commit/420081831f5d4da21ea6bd2d284514ef33e371a1#diff-91b63366a66fe63d633bb36bd5d53cecR279)
it is a temporal fix.

[reloadSurveyAnsweredRatio method](https://github.com/EyeSeeTea/pictureapp/blob/420081831f5d4da21ea6bd2d284514ef33e371a1/app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java#L247)

[DBquery](https://github.com/EyeSeeTea/pictureapp/blob/420081831f5d4da21ea6bd2d284514ef33e371a1/app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java#L349)

I think the query is migrated to dbflow well , but I think it does not cover the case of one single answer.

**Comment by idelcano** [comment]
Related: the incompleted surveys was saving as completed... And it is not removing again.

**Comment by adrianq** [comment]
@idelcano maybe we can close this card or are you thinking about implementing anything? perhaps we can add  a new card more specific when we start working on the pictureapp-malariapp integration
