### ISSUE TITLE
Implement new push/push answer json structure

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1151]

**Comment by ifoche** [comment]
endpoint: https://james.psi-mis.org/eRefWSDev/api

**Comment by manuelplazaspalacio** [comment]
solving issue https://github.com/EyeSeeTea/pictureapp/issues/1084

**Comment by ifoche** [comment]
@manuelplazaspalacio please see below all the optionSets involved in eReferrals app server side:

- DE: eRef - Transaction type --> OptionSet: eRef Transaction Type
Options (code):
   - Issued (ISS)
   - Redeemed-IPC (RDI)
   - Redeemed-Prov (RDP)
   - Reminder (REM)
   - Message (MSG)
   - Call (CLL)

- DE: eRef - Program --> OptionSet: eRef Program
Options (code)
   - Antinatal Care (ANC)
   - Cervical Cancer (CCN)
   - Family Planning (FPL)

- DE: eRef - Service --> OptionSet: eRef Service Provided
Options (code)
   - IUD (IUD)
   - Condom (CON)
   - Pills (PIL)
   - Implant (IMP)
   - Counselling (COUNS)
   - Injection (INJ)
   - None (NON)
   - Other (OTH)

- DE: eRef - Call Outcome --> OptionSet: eREF - Comm Outcome
   - Not connected (NOT)
   - Took service at non-PSI facility (NoPSI)
   - Took service at PSI facility (not e-redeemed) (PSI)
   - Promised to attend (Attend)
   - will not attend (NoAttend)

**Comment by manuelplazaspalacio** [comment]
The optionSets of Transaction type and Call Outcome are not in the surveys.
Instead of that I have:

   - Gender:
      - Male
      - Female
   - Chanel of  referral:
      - Health Facility
      - Group Session
      - Door to Door
   - Civil Status:
      - Unmarried
      - Divorced
      - Married
      - Widowed
   - Ownership of Phone:
      - No Mobile
      - Her Number
      - Husband/Partner
      - Shared



2017-05-16 11:00 GMT+02:00 Ignacio Foche <notifications@github.com>:

**Comment by ifoche** [comment]
@manuelplazaspalacio ok, so they are probably automatically filled in by the WS. For the other OptionSets you mention (Gender, Channel of referral, civil status and ownership of phone) please find here their options with their codes (Sorry they had a different naming convention server side and they're tracked entity attributes instead of DEs)

TEA: CORE - Gender --> OptionSet: CORE - Gender
- Options (code):
   - F (F)
   - M (M)
   - T (T)

TEA: eREF Channel of referral --> This is only configured as a text type, but not with an optionSet, so you can directly send the text options that you had:
   - Health Facility
   - Group Session
   - Door to Door

TEA: CORE - Marital Status --> Like with the previous one, there's no optionSet configured, so just use the options you had:
   - Unmarried
   - Divorced
   - Married

TEA: eREF Phone ownership --> No optionSet either. So options would be:
   - No Mobile
   - Her Number
   - Husband/Partner
   - Shared
