### ISSUE TITLE
Test a change in the database  doesn't require uninstall and install the app

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#116]

**Comment by adrianq** [comment]
@idelcano when you are done with the doc paste the link here please (don't  worry only people with read access will be able to read it).

**Comment by idelcano** [comment]
https://docs.google.com/document/d/1WYgEAgpRtrHL7sCToLn7kdHfEnuPyYa7HJm4yAMhv4M/edit
Any suggestions about the doc is welcomed.
