### ISSUE TITLE
Analyse if any of the permissions asked when installing the app from an apk can be removed

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#117]

**Comment by idelcano** [comment]
I think gradle is adding the necessary permissions for external librerys as GooglePlay services com.google.android.gms:play-services:8.1.0
we have In androidmanifest.xml:
ACCESS_FINE_LOCATION, INTERNET, ACCESS_NETWORK_STATE
But in the installation of the application gradle adds in versio api16:
System Tools: prevent phone from sleeping
Storage: modify or delete the content of your sd card.
Your accounts: use accounts on the device.
Development tools: test access to protected storage.
Your accounts: find accounts on the device.
In version 21:
System Tools: prevent phone from sleeping
Storage: modify or delete the content of your sd card.
Your accounts: use accounts on the device.
