### ISSUE TITLE
DE for ‘phone features’ doesn’t get retrieved in the event report

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#120]
@josemp10 can you have a looked at this? As far as I know the data was properly pushed to the server

**Comment by josemp10** [comment]
They are being retrieved well  to me. Later today, will generete a report,
so Rodolfo can see. But it is working

**Comment by adrianq** [comment]
Ok, I have moved the card to 'in progress'. Please, keeps us updated about it

**Comment by josemp10** [comment]
We can see it is working here:
https://www.google.com/url?q=https://dev.psi-mis.org/dhis-web-event-reports/index.html?id%3DWNwvb3iDPcm&sa=D&ust=1445790027863000&usg=AFQjCNG8FpzZ4OIuZz_Zav18S9ZgmZR7Hw

**Comment by adrianq** [comment]
I already sent a mail to the client pointing to your comment. Let's wait for his answer before closing this issue. Moving to test column in the meanwhile.

**Comment by adrianq** [comment]
Closing this. No answer and  no complain from the client so far...
