### ISSUE TITLE
Review license text

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#122]
Text has CRs, so it doesn’t look well formatted
Also text is too big

**Comment by idelcano** [comment]
I found this on the license:
    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

**Comment by idelcano** [comment]
@adrianq the branch with only the licence text changed https://github.com/EyeSeeTea/pictureapp/tree/license_text
