### ISSUE TITLE
Text when closing an OU

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#129]
@idelcano can you remember me what text we are using at the moment to update the description of the OU?

**Comment by idelcano** [comment]
Android Surveillance App set the closing date to dd-mm-yyyy because over 30 surveys were pushed within 1 hour.

**Comment by adrianq** [comment]
@idelcano Thanks! Let's keep this open for now. The client wants to change the text but he is not sure yet. Will keep you updated!
