### ISSUE TITLE
Introduce "I forgot my password" link in login

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1344]
This task includes:
- [x] Introduction of the link in login screen
- [x] On click, call the WS

This link will call the WS, which will send an SMS. In the call we will include the content of the username field (no new screen will be used). 

In the answer, the web service will answer with:
- Status: Accept/Denied
- Message - Message for acceptance (typically something like "SMS sent to stored phone for the given username") or denial (typically something like "Username or password do not match any register in the server").

- [ ] Show a pop-up with the content of the WS answer or any network error

**Comment by manuelplazaspalacio** [comment]
@idelcano  can you check if the TestWSForgotPassword works to you. It works for me in the androidTest folder but now I changed it to the androidTestereferrals folder and it stopped working. Thanks
