### ISSUE TITLE
Event date vs Time Capture mismatch and timezone problem on survey creation

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1358]
Alpha tester report:
Events with Time Capture = 2017-08-01T00:29:41.179+0100 render as event dates = 2017/07/31. Any reason why that is? I guess that is the date EST but would NOT be the correct date of local Laos time. Maybe this would be problematic for data quality checking. I'm looking at org unit

**Comment by ifoche** [comment]
New information from alpha testers. It looks like this problem happens when you generate an event while your timezone has already passed to a new day but UTC not yet in UTC-4. Please look at [the screenshot](https://camo.githubusercontent.com/c4a3295b05a0294448cabe8d76c1a36d26ded530/68747470733a2f2f776166666c65696f2d6469726563742d75706c6f6164732d70726f64756374696f6e2e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f3537633339616435666334383838306530303630303633322f313235353136633636653832633732386163653231653064343664623937383832363837386462613837653661623763663630646131633336343136376633653739356465653739323163386233373866323132326534333433346430656565316530323061313762386562383333396133623133623734643935613066653464303366306137643937363931336139623838333465623630386265323964393564393961346665646231323934623736303763616464656364356433343063303131643830666535373334613539393439636135306665346665323435353661363162323432652e706e67) but specially, to [this file](https://drive.google.com/open?id=0B7TXlu17DcAbeDROVmVndU4yN2c)

**Comment by ifoche** [comment]
This issue has changed and now represent these 2 things:
- [ ] Time Capture must be moved to be the  time when the user clicks on + (the same as event cpature)
- [ ] When timezone is not UTC, and the timezone has changed the day while UTC didn't there's a mismatch in the event date and the date DEs

**Comment by idelcano** [comment]
This solution still having a problem, but i think this is not important for the reports and i will move the issue to "to test".

For example in the event: https://android.psi-mis.org/api/events/sfbaarPHUsR

The event date was truncated to: 
eventDate="2017-08-10T14:44:14.000"
But the datetime datavalue is saved as:
time capture value="2017-08-10T14:44:14.145-0400"

The datetime is saving the time zone. (-04 00)
But the 145 is not truncated and the eventdate and the timecapture dates has different milliseconds.
I tries to upload the eventdate with milliseconds but when i send it the date was stored with utc 0 zone.
And the datetime dataelement doesn't allow the date without zone.

Is important remember the timecapture datavalue is used to control the quarantine surveys, if we truncates the milliseconds the quarantine system will be less effective.
(matching the surveys with the same day min and second)
