### ISSUE TITLE
Quarantine surveys not pushing

### ISSUE THREAD

**Issue by manuelplazaspalacio** [EyeSeeTea/pictureapp#1388]
If there are quarantine surveys they will never push.
I was putting app offline and at any point the app put the surveys in quarantine, I think it was in the on create method of the BaseActivity.
I think to solve this bug you only need to try to push the surveys in quarantine with the completed surveys in the push method of the WSPushController.

**Comment by ifoche** [comment]
on eRef, quarantine will be simply moved to complete
