### ISSUE TITLE
Add remaining translations

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#139]
@idelcano can you please add the remaining translation? You can find the texts highlighted in this [doc](https://docs.google.com/spreadsheets/d/1P0-7qi8UfoMfk6WhBAAD-90zp4CA89DTMLSczf4Nf08/edit#gid=0) You should have access to the doc.

**Comment by idelcano** [comment]
@adrianq

I checked all translations of the document , not only highlighted text ,
Some text strings was different and changed.

And i remember some english translations was changed
like:

strings.xml: Delete Survey

Delete sent results	លុបលទ្ធផលដែលបានផ្ញើរចេញ


strings.xml: Outlet Code is not active for program. Contact PSI at 123456789

Settings (R3)	Outlet Code is not valid. Contact PSI at 123456789	"លេខកូដកន្លែងផ្តល់សេវាមិនត្រឹមត្រូវទេ។
ទំនាក់ទំនងមក ភី អេស អាយ តាមរយៈលេខ១២៣៤៥៦៧៨៩"

strings.xml: Outlet is closed or blocked. Contact PSI at 123456789

Settings (R3)	Outlet Is Closed. Contact PSI at 123456789	"កន្លែងផ្តល់សេវាត្រូវបានបិទ។
ទំនាក់ទំនងមក ភី អេស អាយ តាមរយៈលេខ១២៣៤៥៦៧៨៩"




And this not exists:


Settings (R3)	Contact PSI at 123456789	ទំនាក់ទំនងមក ភី អេស អាយ តាមរយៈលេខ១២៣៤៥៦៧៨៩
Settings (R3)	Validate Outlet	បញ្ជាក់ថាកន្លែងផ្តល់សេវានេះត្រឹមត្រូវ
