### ISSUE TITLE
Layout modifications

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#150]
- [x] Age question: change the numeric picker for a textfield (integer with mask from 0-99)., answer remains as mandatory
- [x] Remove automatic telephone mask and implement validation system following these rules:
0NN NNN NNNN (last n is optional).
- [x] When entering the telephone number (depending on the device screen size) the floating keyboard may hide the ‘Ok’ button which leads to the final message. Redesign the layout (textfield and button) so that button do not get hidden when setting the telephone number.

**Comment by ivanarrizabalaga** [comment]
@adrianq I have to quit for today.

I will create a PR all those changes and add a small commit tomorrow with the new mask for the telephone.
