### ISSUE TITLE
SDK integration

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#151]
Integrate SDK into the application and use SDK pull/push feature. Application should be compatible with DHIS SDK 2.21. Tests will be performed targeting 2.20 and 2.21 DHIS2 servers (2.22 probably by the end of the release). For servers 2.20, most of the current mechanisms to retrieve and push information will be used. However for 2.21 and 2.22 we have to use the SDK as much as possible in order to communication to the server,

- [x] Identify server version on init /server url change/orgunit. API call: https://hnqis-staging.psi-mis.org/api/system/info
- [x] Implement mechanism in order to allow switching between current behaviour for 2.20 server: Push and Org Unit & Url selection
- [x] Migrate and adapt visitors.
- [x] For 2.21 and above implement:
   - [x] When changing OU and url, download metadata (available OU) and once selected data for the last three months.
   - [x] Push data

Note there are a few API calls in the [PushClient class](https://github.com/EyeSeeTea/pictureapp/blob/1e7948206be314c2f8fb4ee5d877834fb4f3ed38/app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java) that should stay there after the SDK integration. These calls allow to ban a OU when too many surveys has been pushed, checked if a OU is open, etc.

**Comment by ivanarrizabalaga** [comment]
@adrianq The default user 'KHMCS' is not ready in *https://hnqis-staging.psi-mis.org*, I guess this is going to be required to test 2.21 sdk.

**Comment by adrianq** [comment]
@josemp10 Can you please create [this user](https://github.com/EyeSeeTea/pictureapp/blob/1e7948206be314c2f8fb4ee5d877834fb4f3ed38/app/src/main/java/org/eyeseetea/malariacare/network/PushClient.java#L97-L99) in staging so that we can start testing the sdk integration? @ivanarrizabalaga In the meanwhile, can you use your user? Do you have permissions for the OU/server?

**Comment by adrianq** [comment]
@ivanarrizabalaga  A few details to keep in mind:
- Staging will be updated to 2.22 by the mid-end of this week. We will probably also have two dedicated servers with 2.22.
- For  now keep working with sdk 2.21 branch targeting 2.21 staging server. However, once the server is migrated to 2.22 we have to change  to 2.22 sdk branch. I am aware it can be a sort of a pain but I think most of the work will be reused as difference between the two branches (and server versions) are minimum.
- We are aiming the app to work with 2.20 and 2.22. Compatibility with 2.21 is not needed but until we have the 2.22 server we can keep working with 2.21.
- As discussed 2.20 will keep using the current approach while 2.22 will use the SDK. However we can reuse some features for the SDK, for instance log-in system.
- We don't need the data to be downloaded for 2.20.

Please, if anything is unclear let me know and we can schedule a meeting. It has been a pain to get a clear idea of what we want (too many actors and technologies) but I do think now we have a much better understanding...

**Comment by ivanarrizabalaga** [comment]
@adrianq hnqis-staging is pulling data ok without any error.

I'm still working on the visitors (I'm almost there) since I need to change in order to keep the local info and link this properly with the orgunits, surveys and values.

**Comment by adrianq** [comment]
Great! I think you only have permissions for the Cambodia Org Units. Is this correct @ivanarrizabalaga?
Did you test the pull process with a 2.20 server? Was it successfull?

@ifoche it looks like if you have permissions for not too much data the api is working fine. Therefore, it is not a problem with the api in general, right?

**Comment by ifoche** [comment]
mmm, I don't know, I'm going to retest because from my mail to BAO people to now, that server has doubled his memory (I've just checked looking at what I sent to them and looking again to the memory size now). It now sais:
Server memory:
Mem Total in JVM: 1602 Free in JVM: 831 Max Limit: 1602

Let me do the test again to check that it's still not working with HNQIS

**Comment by ifoche** [comment]
Nothing, still not working, I've replicated Ivan user, but however, it's very very strange, as @ivanarrizabalaga  has permissions also for the same amount of OrgUnits and he is even superuser in the server

**Comment by ifoche** [comment]
@ivanarrizabalaga just a question, you're downloading both data and metadata with the sdk pull and the only modification that you're doing in comparison with HNQIS, is that in Mal Surveillance you just translate the data and not the metadata...but for the rest it's the same, isn't it? Did you modified anything else in the pull process? Because I'm launching a pull with a user that is a copy of yours and I'm not being able to get the metadata/data downloaded in HNQIS against hnqis-staging...I'm a bit lost here...

**Comment by ivanarrizabalaga** [comment]
@ifoche, exactly just a normal pull with a local filter to skip data that
doesnt belong to picture program.

But in the terms of the server is exactly the same. Weird!

**Comment by adrianq** [comment]
@ivanarrizabalaga are you working with the sdk 2.22 or are you still working with the 2.21 branch?

**Comment by ivanarrizabalaga** [comment]
@adrianq you're right, yesterday I couldnt move into 2.22 because the app was not compiling and couldnt add more stuff to the mix.

I'm into 2.22 now, I'll keep you informed as soon as I get the details.

**Comment by ivanarrizabalaga** [comment]
@adrianq  

The **Telephone** question has different UIDs in the server and the local csv file:

 - **File**: rDubghVv1L8
 - **hnqis-staging**: RuNZUhiAmlv
