### ISSUE TITLE
Implements metadata version logic

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/pictureapp#1547]
Verify metadata version stored in namespace of data storage in server

**Comment by ifoche** [comment]
version namespace already implemented. Just use this call to obtain it:
https://dhis2.asia/cnm_android/api/dataStore/admin/version

To change it (for testing), it's as simple as executing the following call:
```
curl "https://dhis2.asia/cnm_android/api/dataStore/admin/version" -X PUT -d "{\"version\":\"<N>\"}" -H "Content-Type: application/json" -u <user>:<pass> -v

Where <N> is the version number and <user>:<pass> the credentials
```
