### ISSUE TITLE
Review CSVs

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1635]
- [x] Review poeditor keys
- [x] Review options order at least for civil status & current method
- Special attention to MZ & ZW

**Comment by manuelplazaspalacio** [comment]
Strings duplicated and changed (left side string in web, right string in app):
ipc_issueEntry_q_furtherInformationConsent => ipc_issueEntry_q_phoneContactConsent
ipc_issueEntry_q_generateVoucher => ipc_issueEntry_q_isClientReferred
