### ISSUE TITLE
POEditor API strings update

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1652]
Given the POEditor endpoint for the strings, on app start, retrieve all the strings and update the strings & translations table

**Comment by ifoche** [comment]
Description of POEditor endpoint [here](https://poeditor.com/api_reference/). It looks like we would be using the following actions:
- list_languages
- view_terms

**Comment by ifoche** [comment]
We would need to add retrofit models to match the API response & define the POEditor token inside the config.xml file that's in the gitignore. For the token let's talk through the Android Team chat

**Comment by Amejia481** [comment]
Hi @ifoche!

After going through the requirements, I have some questions,
Could you give me a :hand:(hand), please?

1. After the app loads the strings from POEditor for the first time, should I assume that strings are not going to be updated?
1.1. Which strategy are we going to use for strings update?
2. What about if I lose internet connection while I'm downloading the
string for the first time?
3. Should the number of languages that the app supports are fixed or you can add I new one without updating the app? Maybe this endpoint could be helpful for this case: [List Project Languages](https://poeditor.com/api_reference/#list_project_languages).

Thanks in advance!

**Comment by ifoche** [comment]
Just for the record, and according to our conversation, I answer here what we just talked.
1) We need to update both languages and terms separately on every single app start. In one hand the languages using the list_languages call, that would create a new translation in case needed. In the other hand the terms, that I would suggest (if that exist) to sort the terms call showing the most recently updated first, and checking that date and storing it in the DB would give you the capability of only updating the terms whenever it's really needed
2) For the first DB population, we would use a new CSV for which we would modify the PopulateDB class including the new table(s) with the strings that currently exist in strings.xml
3) As explained in 1), a new language could be added after the app's been deployed

Thank you for the efforts!

**Comment by ifoche** [comment]
just for the record, after our conversation @xurxodev, @Amejia481 and myself, we decided to avoid the DB population from CSVs and change the getInternationalizedString from Utils to get the string from DB if any, and otherwise look for it in the Android system. All controlled by a gradle variable (to avoid unnecessary lookups on other variants)
