### ISSUE TITLE
Config file downloader

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1654]

**Comment by ifoche** [comment]
The endpoint that will be used is [this one](https://docs.dhis2.org/2.27/en/developer/html/webapi_data_store.html)

**Comment by ifoche** [comment]
@Amejia481 the structure of the config file has slightly changed. The new one contains also a config reference key so different tests can be done against the same OU. Please take a look at the new one [here](https://data.psi-mis.org/api/dataStore/Connect_config/dcSettings) (to access, enter using the app fix credentials). Could you please adapt our retrofit parser to the new one?

**Comment by ifoche** [comment]
Please check also that we're compatible with the latest config files version. The config_file folder that I just shared with you contains a couple of examples

**Comment by Amejia481** [comment]
Sure @ifoche!
