### ISSUE TITLE
Login improvements

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1655]

**Comment by ifoche** [comment]
There are 2 type of logins: soft login (when there's already a user logged), full login (when it's the first time or the user just logged off). This is already recognized to auto-fill the Username field.

Changes:
- [x] "User Name" must read "User Code"
- [x] "Password" must read "PIN"
- [x] "I forgot my password" must read "I forgot my PIN"
- [x] Another link must appear below "I forgot my PIN" saying "advance options"
- [x] Server URL field moved to advanced option section
- [x] On soft login, User code shouldn't be editable
- [x] On click in "advance option", a new button must appear. If we're in a soft login, the new button is log off. If we're in a full login, the button will be demo.

**Comment by Amejia481** [comment]
I believe that you also mentioned if "advanced option" is not clicked the field  "Server URL" shouldn't be visible, and when it's clicked it should appear? 

Could you confirm that info, please?

**Comment by Amejia481** [comment]
# All the label text,  should be the same to both **Soft login** and **Full login**?

For example:
## Should be the same text for both **Soft login** and **Full login**?

 **Soft login fields** :
"User Code"
"PIN"
"I forgot my PIN"

 **Full login fields** :
"User Code"
"PIN"
"I forgot my PIN"

## **Or should be different for each logging type?**


 **Soft login fields** :
"User Code"
"PIN"
"I forgot my PIN"

 **Full login fields** :
"User Name"
"Password"
"I forgot my password"

**Comment by Amejia481** [comment]
I'm a little confused by this task:  

- On click in "advanced option", a new button must appear. If we're in a **soft login**, the new button is **_log off_**. If we're in a **full login**, the button will be **_Log off_**.

Both (soft login and full login) should have the same button?

Could you give me a hand there, please?

**Comment by ifoche** [comment]
@Amejia481 let me answer your questions:
- You're right, server URL field must be moved to advance options (I've included it in the task description)

- The fields are exactly the same in full and soft login. In fact, unless you find it necessary, both would be implemented through the same interface, that simply would show or hide some components. So the text is the same

- From user perspective, there's a single button in the advance option. If you're in a full login, the button is demo (I wrote logoff by mistake in the description, now it's fixed). If you're in a soft login, the button is log off. That means both buttons are probably there in the interface but you decide to show or hide one or the other depending on the type of login that you're in.

Please don't hesitate to ask if you  have any further question

**Comment by Amejia481** [comment]
#  Full-login
## Demo Video
https://drive.google.com/file/d/1XL1shtYtggS5df5_wNy6h6o7JL7SIZoR/view?usp=sharing

### Without Clicking "Advanced Options" 
![image](https://user-images.githubusercontent.com/773158/32854852-57d6ab2a-ca16-11e7-90f4-c38d3f13b456.png)

### Without Clicking "Advanced Options"
![image](https://user-images.githubusercontent.com/773158/32854900-781680e0-ca16-11e7-85a9-e549242ec75a.png)


# Soft-login
## Demo video.
https://drive.google.com/open?id=1vcjSlkZYifg4FRfnrt4ATdozLb2UfbpM

### Without Clicking "Advanced Options" 

![image](https://user-images.githubusercontent.com/773158/32854700-db7b934c-ca15-11e7-839b-df7ecd2eab9d.png)

### Without Clicking "Advanced Options" 
![image](https://user-images.githubusercontent.com/773158/32854792-29ac24a0-ca16-11e7-9e02-2d5fe01a88b6.png)

**Comment by ifoche** [comment]
Before merging, just for the record, we need to:
- [ ] change "Advanced Options" by "Simple Options" when advanced option is already clicked
- [ ] change URL to production one
