### ISSUE TITLE
Minor Layout Improvements

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#168]
- [x] Improve layout for age and telephone number:
   - [x] Shorter and thicker
   - [x] Increase font size by default
   - [x] Display keypad for age textfield
   - [x] Make button larger (Ok in Khmer should display in one line)

**Comment by ivanarrizabalaga** [comment]
@adrianq, I edited this card so that each card matches a branch.

The branch for this card is **age_telephone_layout**
