### ISSUE TITLE
On soft login, autofocus on pin field

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1723]
On a soft login, the focus must be automatically taken by the pin (password) field, so the keyboard is shown immediately and the user doesn't waste too much time to introduce it

**Comment by Amejia481** [comment]
Close by Pull request #1670

**Comment by ifoche** [comment]
PIN is autofocused but keyboard is not deployed. Can you please add the code to deploy the keyboard? But before doing it, it may be implemented in #1757. @manuelplazaspalacio can you confirm whether or not that issue deployes the keyboard? If so, @Amejia481 can you please in the framework of this issue merge development into that branch (#1757)? Thanks!

**Comment by manuelplazaspalacio** [comment]
This bug is solved in https://github.com/EyeSeeTea/pictureapp/pull/1757/commits/cacf44a99888b12101a114fab093b9f714c62efd
In the LoginActivityStrategy

**Comment by ifoche** [comment]
ok, thanks @manuelplazaspalacio. So @Amejia481 can you please merge development into #1757 branch? Thanks!

**Comment by Amejia481** [comment]
Sure @ifoche!

**Comment by Amejia481** [comment]
@ifoche  I merge development into #1757
