### ISSUE TITLE
Add last commit to about us

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#175]
See https://github.com/EyeSeeTea/malariapp/pull/827

**Comment by ifoche** [comment]
And also this commit f2bac9e592093187fd0952fa64f76f06d7071516

**Comment by idelcano** [comment]
And also this commit [EyeSeeTea/malariaApp @ f2bac9e](https://github.com/EyeSeeTea/malariapp/commit/b7115dd79671e27595f4842ba2b98f2859ff2740)
