### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#18]
- [x] Modify settings in order to only display Font Size and Org Unit
- [x] Org unit displays as a free text field (to be used as the Org Unit code).  The user can start a survey without any org unit is set and it will be updated later on. There will be just one org unit per device.

**Comment by ivanarrizabalaga** [comment]
@adrianq
Settings are mostly ready.
The push is 'prepared' to do the 'pull' for the Org Unit UID before doing the push.
