### ISSUE TITLE
Mandatory sign on the left for RADIO_GROUP_HORIZONTAL questions

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1806]
if you configure a question like this...

```
"dataPointRef": "yearOfBirth",
"poTerm": "ipc_issueEntry_q_yearOfBirth",
"defaultName": "Year of Birth",
"controlType": "RADIO_GROUP_HORIZONTAL",
"options": [{
        "value": "true",
        "poTerm": "",
        "defaultName": "true"
        }]
```

...you end up with a yes only question (this is ok) but the mandatory asterisk appears on the left.

**Comment by Amejia481** [comment]
it looks pretty similar to this issue #1798 that is already fixed.
Is it any differences between them?

**Comment by ifoche** [comment]
completely right. I forgot it was already waiting for approval. I'm sorry for that
