### ISSUE TITLE
Add language to URL on webviews

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1813]
Please add the parameter...
```
&lang=<code>

where <code> is es, en, pt...
```
...to the end of the url loaded into the webviews. Please make sure to pass the language code that is defined in settings or the default language in case system default option is configured

**Comment by Amejia481** [comment]
@ifoche 
I manually simulated appending different language codes like these ones:

**&lang=pt**
https://apps.psi-mis.org/connect/pages/ipc.html?skipHeader=true&action=ipcOpenReferrals&userName=userName&password=password&lang=ne

**&lang=sw**
https://apps.psi-mis.org/connect/pages/ipc.html?skipHeader=true&action=ipcOpenReferrals&userName=userName&password=password&lang=sw

**&lang=np**
https://apps.psi-mis.org/connect/pages/ipc.html?skipHeader=true&action=ipcOpenReferrals&userName=userName&password=password&lang=np

on the browser but I continue getting the page in English.
**Is it this feature TURN ON the website side?**

**Comment by ifoche** [comment]
@Amejia481 no it isn't. They will introduce it server side on Saturday. However, we need to leave everything prepared to work. I guess that a minimum test could be added to check that the URL contains the parameter, but please do not implement very complicated tests, just that simple one.

**Comment by Amejia481** [comment]
Sure!
I've added the test!

Note:
When I test with the Nepali language it shows a bunch of question marks(?)
with the other language works correctly!

![screenshot_1518451162](https://user-images.githubusercontent.com/773158/36106140-e45c160e-0fec-11e8-8221-5f5abf5e240d.png)


![screenshot_1518451193](https://user-images.githubusercontent.com/773158/36106115-d3393c62-0fec-11e8-971a-4dc225da5881.png)

![screenshot_1518451174](https://user-images.githubusercontent.com/773158/36106125-d8ca3096-0fec-11e8-9c27-0296fe4f0af5.png)

**Comment by ifoche** [comment]
@Amejia481 and does this happen when you call on a normal browser? I mean, does this have anything to do with the webview component or is it coming like that from the WS?

**Comment by Amejia481** [comment]
It coming this way from the WS
![screenshot_20180212-124521](https://user-images.githubusercontent.com/773158/36108263-c95276cc-0ff2-11e8-978b-9e7682d4a76f.png)

**Comment by ifoche** [comment]
ok, then I guess there's nothing we can do. Thank you!

**Comment by Amejia481** [comment]
:+1:
