### ISSUE TITLE
Change stock automatic registering logic

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1850]
Currently a stock expense type survey is automatically created when a MCS survey is created. We need to change that to only those programs that have an associated stock program in the ProgramProgramRelation table.

**Comment by Amejia481** [comment]
- [x] Create programProgramRelation.csv and populate db onStart()
- [ ] Search for the logic that creates automatic  stock survey and edit to use 
        programProgramRelation table.
