### ISSUE TITLE
space between text edit text is too big

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/pictureapp#1899]
## User Report
on the program VMW question patient name 

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot408983421.jpg)
## Device Info
```
Time Stamp: 2018-03-13T15:58:22 UTC
App Version: 0.2.0 (51)
Install Source: Unknown
Android Version: 7.1.1 (25)
Device Manufacturer: MOTOROLA
Device Model: MOTO E (4) PLUS
Display Resolution: 1184x720
Display Density (Actual): 320dpi
Display Density (Bucket) xhdpi
---------------------

```

**Comment by Amejia481** [comment]
Also the background and style color doesn't match with the rest of the questions
![screenshot_20180313-120026](https://user-images.githubusercontent.com/773158/37353747-5cf6dcae-26b6-11e8-9bcd-fa2fe81065e0.png)
