### ISSUE TITLE
month question doesnt match with style of the other questions

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/pictureapp#1900]
## User Report
background color and style of the month question  on program VMW

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot106458515.jpg)
## Device Info
```
Time Stamp: 2018-03-13T16:04:29 UTC
App Version: 0.2.0 (51)
Install Source: Unknown
Android Version: 7.1.1 (25)
Device Manufacturer: MOTOROLA
Device Model: MOTO E (4) PLUS
Display Resolution: 1184x720
Display Density (Actual): 320dpi
Display Density (Bucket) xhdpi
---------------------

```

**Comment by Amejia481** [comment]
An example of other questions style
![screenshot_20180313-120026](https://user-images.githubusercontent.com/773158/37353964-e8a85c96-26b6-11e8-9b55-61e1e767c870.png)
