### ISSUE TITLE
Create CSVs to model workflow as parent-child relationships

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#191]

**Comment by ifoche** [comment]
Model following workflow

![s5 taxing flowchart 10 -2](https://cloud.githubusercontent.com/assets/10931645/15679211/52343b74-2751-11e6-9de5-c653fb185dd1.png)

**Comment by ifoche** [comment]
Just to give a little bit more details:
![modifications_1](https://cloud.githubusercontent.com/assets/10931645/15682081/49db82e2-275c-11e6-9798-041c88795295.png)

![modifications_2](https://cloud.githubusercontent.com/assets/10931645/15682084/4cfc353e-275c-11e6-8510-995741241a6b.png)

![modifications_3](https://cloud.githubusercontent.com/assets/10931645/15682096/548db9e4-275c-11e6-94df-49c56105dd56.png)

![modifications_4](https://cloud.githubusercontent.com/assets/10931645/15682161/ad8d7412-275c-11e6-85eb-d2035fd21e7c.png)

**Comment by ivanarrizabalaga** [comment]
@ifoche the translations sheet needs number 10,11,12 in khmer (no we got more questions).

**Comment by ifoche** [comment]
@ivanarrizabalaga for the moment I think you can get it from google translate (it will propose 10, 11 and 12, but by clicking on alternative translations you can get it)

BTW, @ivanarrizabalaga @idelcano . Please note that I've just shared with you the new flowchart (with minimum modifications if I'm not bad...just 4 options for one of the questions). I'm attaching it here too and removed old one from this card to avoid confusion.

![s5 draft final flowchart](https://cloud.githubusercontent.com/assets/10931645/15741234/10f566b0-28b9-11e6-9ca4-45efc8d3a82f.png)

**Comment by ifoche** [comment]
Useful information you may need. I paste you here the UIDs and option names for the optionSets.

UIDs for the DEs:
Age - JMM92njKuSc
ASMQ - mCSYUwYXnnj
Case Classification - ff3lAAW1VLh
DHA-PIP - LRzOBn2rZA3
Gender - uuudizosfpU
Not tested reason - fkBDnkiQbWY
Occupation (previously Risk group) - Zf8O1uzl3JJ
Phone - rDubghVv1L8
RDT - OEdLEjF6Z8p
Referral - Bi2NfBG8LGJ
Specie - X6RFHreAu0L
Treatment - fNpYtVaL7OV
Phone features - RuNZUhiAmlv

OptionSets with their options:
KH_SRV-ASMQ (Text):
- 1.5 Pills
- 3 Pills
- 6 Pills
DHA-PIP (Text):
- 4.5 Pills
- 6 Pills
- 9 Pills
- 12 Pills
KH_SRV-Gender: (remains intact)
KH_SRV-Not-tested (Text):
- Patient refused
- Danger signs
- RDT stock out
KH_SRV-Occupation (Text):
- Forest Worker
- Security Military
- Plantation Worker
- Construction Mine Worker
- Other
KH_SRV-RDT: (remains intact)
KH_SRV-Referral:
- Child Under 5
- Pregnancy
- ACT Stock Out
KH_SRV-Species: (remains intact)
KH_SRV-Treatment (Text):
- AS/MQ
- Referral
- DHA-PIP
KH_SRV-YesNo (YesNo - for the question of Case classification):
- Yes
- No

**Comment by ivanarrizabalaga** [comment]
@ifoche, the right options are the ones in the tables? I guess so, for instance in the table the DHA options are:

Age 5 - 10 Years Old\nWeight 19 - 30 Kilograms
Age 10 - 15 Years Old\nWeight 30 - 40 Kilograms
Age >15 Years Old\nWeight 40 - 60 Kilograms
Age >15 Years Old\nWeight >60 Kilograms

where in the last image tha captions are:

4.5 Pills
6 Pills
9 Pills
12 Pills

I think the table are the right ones and the others are the quick manner to refer to the options, am I right?
