### ISSUE TITLE
Answers shown multiple times

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/pictureapp#1989]
## User Report
I just did a clean login, filled in a form and I'm getting this

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot468410385.jpg)
## Device Info
```
Time Stamp: 2018-03-23T15:25:28 UTC
App Version: 1.0.4 (32)
Install Source: Unknown
Android Version: 7.1.1 (25)
Device Manufacturer: BQ
Device Model: AQUARIS X PRO
Display Resolution: 1920x1080
Display Density (Actual): 408dpi
Display Density (Bucket) Unknown
---------------------

```

**Comment by manuelplazaspalacio** [comment]
I couldn't re produce this bug, I tried to reproduce this bug with the same user and different phones/emulators:
-Emulator Nexus One API 25 7.1.1
-Emulator Nexus 10 API 19 4.2.2
-Emulator Nexus 5 API 21 5.0.2
-OnePlus A5010 API 26 8.0.0
-Samsung SM-G530FZ API 21  5.0.2

**Comment by ifoche** [comment]
let's close it. I've been also unable to generate the same problem again and the client didn't report it
