### ISSUE TITLE
Add Time Capture and Time Sent control DEs

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#199]

**Comment by ifoche** [comment]
Look in #191 for their description

**Comment by idelcano** [comment]
@Ifoche i have some questions about this issue.

Is the "Time capture"  the creation date?

Is the "time sent" the completion date?

and more important.

I am not sure if i understood the issue 100%.

I did two steps:
Step 1: I added the TAG_DATETIME_CAPTURE and TAG_DATETIME_SENT HardCoded Uids (like the TAG_PHONEMETADATA uid).
I think these control dataelements not exists at this moment in the server.

Step 2: I include these values(datelement uid+ date value) to the  push(i include that in the api pushclient, and in the ConvertToSdkVisitor).

Is it correct?
Is necessary some thing more?

**Comment by ifoche** [comment]
@idelcano,
For now, you can set the "Time capture" to the creation date if you want. I'm not sure if they want the completion date, better than the creation.

The time sent is the date when the survey was sent to the server. It must be updated on each push try, so it's not the completion date. Can you change that?

Regarding the UIDs, yes, at this moment we don't have the UIDs for the DEs. I'm waiting for the client to give me permissions. In the meanwhile, it's ok if you just use fake ones.

**Comment by ifoche** [comment]
Just for the record. The UIDs are the following:
Time sent - aBahytzj2u0
Time Capture - qWMb2UM2ikL
