### ISSUE TITLE
Remove UnkUvjuDrVO DE from program stage at dev server and test the app behavior

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1991]

**Comment by idelcano** [comment]
@ifoche i detected two problems related with some combinations without treatment, for example-> 1 age, pregnant, mixed.

With that combination the stock survey is empty, and a empty survey block the push

The malaria survey doesn't have treatment, and the survey answered ratio is wrong, this survey is never set as completed.

When you restart the app, the surveys in progress and related stock surveys are deleted, the push is working again.
