### ISSUE TITLE
Modify Application

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#2]
- [X]  Review gradle
- [x] Hide login/password dialog
- [x] Skip create activity
- [x] Remove dropdown menu
- [x] Modify tabs/header logic
- [x] Remove general and composite score

**Comment by adrianq** [comment]
![screenshot from 2015-07-20 14 28 31](https://cloud.githubusercontent.com/assets/6850223/8776804/b27f140e-2eeb-11e5-8265-a94a681456a4.png)

**Comment by ivanarrizabalaga** [comment]
@adrianq I going to create a new issue for the dashboard since it is not really related to rest of mini tasks and probably required more changes

**Comment by adrianq** [comment]
@ivanarrizabalaga Makes senses! I added this task here because it was sth that was asked in the very last minute...
