### ISSUE TITLE
Push

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#20]

**Comment by adrianq** [comment]
This is the call for getting the orgunit code:
......./api/organisationUnits.json?paging=false&fields=id&filter=code:eq:{codigo_org_unit}

For this first release the code is KH_Cambodia:
......./api/organisationUnits.json?paging=false&fields=id&filter=code:eq:KH_Cambodia

If correct we will get sth like this:
{
organisationUnits: 
  [
    {
      id: "u5jlxuod8xQ"
    }
  ]
}

If it can't find an answer we will get sth like:
{
organisationUnits: 
[]
}

Although for this first release we wont have this problem it would be good to have some kind of validation and show an error dialog in case it fails.

**Comment by ivanarrizabalaga** [comment]
@adrianq First version ready, looks like some adjusts are needed to consume less battery and some corner cases (ex: what to do when no location is available?)
