### ISSUE TITLE
VMW cases does not appear in the web

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2019]
This is the alpha tester report:
I was using my user ppagalday and the cnm_android server. My phone IMEI is assigned to Bantey Neang (VL0102010300), when I report a case, the case is never uploaded, after a while they disappear from the main screen and there are no events in the Web for that org unit. Sent it to you via email

**Comment by manuelplazaspalacio** [comment]
This issue was an error in the server configuration that @ifoche solved. The problem was that the OrganisationUnits VL were not related with the VMW program.
