### ISSUE TITLE
Create new stock control screen

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2033]
- [ ] Create base layout for the screen

Rows:
- Receipt
- Used Today
- Issues
- Available

Columns:
- Drugs + RDT

- When doing the query to calculate the numbers, start alwasy from last balance in the DB. 

- [ ] Include the + button just like in the list version of the stock module. Maybe we can re-use part of the stock fragment layout?

- [ ] It will be a replace of the stock module, so create a gradle variable to decide if the stock module is shown as a list or as a table, and load one fragment or the other depending on that

**Comment by ifoche** [comment]
Please start the development from development branch

**Comment by manuelplazaspalacio** [comment]
This is not for this app
