### ISSUE TITLE
Inter-app voucher creation while soft-logged

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2034]
- [ ] Create intent on login screen so other apps can create an intent to the app. 

- [ ] Create json parser to unmarshalling from the intent

- [ ] The credentials will be embedded in the request, so they will be used to create a login and then open the voucher creation screen filling in with the provided data

- The login only works if it's a soft login

- The json will be pairs key:value where the key is the property used for each question in the WS submission

**Comment by ifoche** [comment]
The format for the json is the following one:
```
{
	"auth": {
            "userName": "" [optional],
		"password": "" [optional]
	},
	"values": {
		"key": "value",
		"key_does_not_exist": "value" → Ignore
	}
}
```

**Comment by ifoche** [comment]
**Attention: New requirement!!!** In case auth parameters are not provided in the intent (they are optional), the login must allow the user to enter them (only for soft-login)

**Comment by ifoche** [comment]
Situations to manage:
- Success: everthing goes fine, and Connect take control, a form is open and the user can continue filling in the form
- User logged is different. Show a toast with the error and close connect
- No user logged in. Show a toast with the error and close connect

**Comment by idelcano** [comment]
@ifoche what is the expected behavior when the user is logged and the other app send the user with a invalid password?
