### ISSUE TITLE
Check swipe

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/pictureapp#21]
Swipe is not working smoothly

**Comment by ivanarrizabalaga** [comment]
@adrianq

The last PR includes some improvements but it is not 100% smooth, give it a try.

**Comment by adrianq** [comment]
@ivanarrizabalaga It works much better but still we need to improve it a little bit. Anyway, thank you for this

**Comment by ivanarrizabalaga** [comment]
@adrianq Finally I manage to make it work smoothly (quite tricky but clean), no side buttons.
