### ISSUE TITLE
Change splash screen logo by connect one

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2100]
Just like we did in HNQIS

**Comment by ifoche** [comment]
[Please find the svg file here](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e12dad64acc92700d55240/125516c66e82c728ace21e0d46b9c6cf76d3d5aad9bfba1bf65ea7c6714724767b55a67b74d1b52bbd1b79585b5d1aa446505f16a8aadd7aa3e06875890e0de8d33b0e7dc73f40a9ba841abd08bc728e4ed3e7bb834ec2e03c70e589da1a6b1a051fdcfa5430a79c4dc90ca718e54c50f6163067e327622d11c04a77253a6177affedf5085d668a4ee152a04c1ebb1f91612a77f8dce0a76355558fb2c63e40a598868ca43785db9e3c6ff1f190c1909ceb99589e9e789352176444f04c376ed554a57ce8044833acb3e98537a6c4d6c02db4e96a937d59cc2fb6d2982b4e960686fcd12988cd6e9dbc51b1bbce1e8fc8fcfcc670a5e01d8969bc27fea07c5c8c63226c07a433f2295c5.zip)

**Comment by idelcano** [comment]
This issue is not necessary. The app is showing the connect logo in splash screen now.

**Comment by ifoche** [comment]
@idelcano actually it was my mistake, the requirement is not for the splash screen but for the progress activity...where we have the DHIS 2 number with the spinning circle. Re-opening it
