### ISSUE TITLE
Refactor in progress surveys deletion system

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2120]
Currently we're deleting every single survey in progress each time we access dashboard. This was a measure that we introduce to avoid blanks long time ago, but we demonstrated also long time ago that blanks came from other blank sources, different than this. The goal of this issue is to think a bit if this code is strictly needed, or if it's simply something that make things more complicated without adding any significant value. For example...In which situations we will need this? Can we simply move it to EyeSeeTeaApplication on create and just manage the event when the app crashes while the user was fillling in a form?

**Comment by idelcano** [comment]
@ifoche  

The surveys with "in progress" state are only possible in two cases.
When a new survey is created, and when a survey is created from other app.

When the survey is created in other app, a survey in progress will be during the Splash screen.

In that case, the deletion of in progress survey has sense on dashboard load(if the auth is correct a flag is set on login activity to avoid this deletion). 

We can move the deletion of suverys created in the SpashScreen to the loginActivity.

Other case:
The survey could be not removed if the mobile shutdown without close the app.
To prevent that case we can move the remove of surveys in progress to the EyeSeeTeaApplication class.

The in progress surveys are used to load the active survey when the user lock/unlock the screen when a survey is open, or when other app creates a connect voucher.
In that cases the app load the first in progress survey persisted in database.

We can move the remove of in progress surveys to before lock a open survey  and before create a new in progress survey from other app.
