### ISSUE TITLE
multiple items selected

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/pictureapp#2134]
## User Report
when the list of larger than the screen, multiple items appear as selected

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot731334408.jpg)
## Device Info
```
Time Stamp: 2018-06-04T07:33:21 UTC
App Version: 1.1.4 (54)
Install Source: Unknown
Android Version: 7.1.1 (25)
Device Manufacturer: BQ
Device Model: AQUARIS X PRO
Display Resolution: 1920x1080
Display Density (Actual): 408dpi
Display Density (Bucket) Unknown
---------------------

```

**Comment by ifoche** [comment]
![Screenshot_20180604-093444 (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e12dad64acc92700d55240/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc791077276454fa7824d1b768f7133243434d0eee1e020a17b8eb8339a3b36d23df5a5fe9846a5e73c36b12aeb88216bd53b875da5d99a4fedb1294b7607caddecd5d340c041083fe5837a89942cf51f34fe74551b65e.png)
