### ISSUE TITLE
tab buttons disappears

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/pictureapp#2155]
## User Report
I moved between tabs and click reload monitoring all time and tab button disappears

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot1587382102.jpg)
## Device Info
```
Time Stamp: 2018-06-13T06:23:47 UTC
App Version: 1.2.0 (57)
Install Source: Unknown
Android Version: 7.0 (24)
Device Manufacturer: XIAOMI
Device Model: REDMI NOTE 4
Display Resolution: 1920x1080
Display Density (Actual): 480dpi
Display Density (Bucket) xxhdpi
---------------------

```

**Comment by idelcano** [comment]
I could not replicate again
