### ISSUE TITLE
First time you install elements it doesn't work

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2165]
If you just install elements from here: https://rink.hockeyapp.net/apps/458abb63bfb442b0afc8989fd0e8b853 

...and you then launch connect. When you create a voucher it asks you for the permissions for elements but it doesn't launch elements

**Comment by manuelplazaspalacio** [comment]
Could not solve this sdk bug, I try calling different methods from the sdk when activating  setting preference but that not show the  permissions (initElementSDK, deleteUser, requestSyncState).
I try to execute the SDK in the main thread.
And when I check the response when activating the permissions is the same response as when the user clicks on back when entering elements activity.
