### ISSUE TITLE
Cases not uploaded in the background

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2183]
If the app goes to background, the push service stops. We need to keep it working

**Comment by xurxodev** [comment]
@ifoche I can't reproduce the bug, I have created surveys and then I navigate to another app or press home button, the surveys always sent to the server from background. I have tested with HC and VL org units.
I have reviewed the code and de alarm only is cancel by logout action.

**Comment by ifoche** [comment]
They're rechecking but in case it helps, they've just said that the issue occurred in 4.4 devices

**Comment by ifoche** [comment]
Solved in #2196
