### ISSUE TITLE
Substitute dataStore calls

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/pictureapp#2249]
Substitute dataStore calls so their URL no longer use DHIS2 server setting, but WS one (the endpoint is not yet available)

**Comment by ifoche** [comment]
We can proceed with this task. They're asking for introducing 3 settings:
- Program configuration URL
- Program configuration username
- Program configuration password

Those 3 settings would be used to decouple the app from DHIS2. They will point now to DHIS2 datastore, but if at some point it's changed to a WS with basic auth, it would just be a matter of changing the settings and everything would continue working.

**Comment by ifoche** [comment]
@idelcano they've created new credentials for the dataStore. It was not necessary, but let's use what they prefer by default. I'll send you through slack to avoid posting them in a public space
