### ISSUE TITLE
Create new Release tag in github for S5 and L1

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#226]

**Comment by adrianq** [comment]
What do you want me to do? Is this about creating release 4.1 at GitHub?

**Comment by ifoche** [comment]
Yes, basically, I merged development with master branch, but I didn't create the github release. I didn't know about the version number that was supposed to be for our repo...and I preferred to wait for you to come back.

**Comment by adrianq** [comment]
Ok, let's talk about this on Monday. Version numbering is a kind of mess after so many back and forths with the Google Play and the users...

**Comment by adrianq** [comment]
As discussed with @ifoche we will skip S4.1 and we will tag/release S5 as 1.2.2. This will happen on 22th June.
