### ISSUE TITLE
Push last forever

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/pictureapp#2288]
## User Report
Push while elements produced an error

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot5444323701702547939.jpg)
## Device Info
```
Time Stamp: 2018-10-12T11:33:16 UTC
App Version: 1.2.2 (59)
Install Source: Unknown
Android Version: 8.1.0 (27)
Device Manufacturer: BQ
Device Model: AQUARIS X PRO
Display Resolution: 1920x1080
Display Density (Actual): 408dpi
Display Density (Bucket) Unknown
---------------------

```

**Comment by ifoche** [comment]
Just took more time but it worked at the end
