### ISSUE TITLE
Introduce a review screen

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#230]

**Comment by ifoche** [comment]
Only on positive answer

**Comment by ifoche** [comment]
We need to:
- [ ] Update this branch with development branch
- [ ] Move layouts and other variant-specific things to each variant
- [ ] Put laos graphics and layout
- [ ] update cambodia graphics with the last version
- [ ] put a per-variant switch to activate/deactivate this feature. Activated by default in laos, deactivated in cambodia

**Comment by idelcano** [comment]
The Review Screen is merged and working, but we need review to finish this issue:

-If the graphics was changed.I didn't have new graphics of cambodia, and i didn't have review screen graphics for laos).

-Could be necessary move to their variant all the new modifications in the layouts after merge and finish all.

**Comment by ifoche** [comment]
[laos devices](http://www.laomobilegroup.com/mobile-phone-samsung.html)

**Comment by adrianq** [comment]
@idelcano As you recommended me, I will merge this PR after we are done with the Cambodia release. Hopefully, early next week.

**Comment by adrianq** [comment]
This is the current status of the review screen as sent by @idelcano yesterday:
![2016-08-03](https://cloud.githubusercontent.com/assets/6850223/17432457/4d5e76f8-5af7-11e6-9f86-4c11205ecaa2.png)

Probably require some comestics...
