### ISSUE TITLE
refactor to avoid invoke many times getInternationalizedString because the code is low readable.

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/pictureapp#2334]

**Comment by ifoche** [comment]
Postponing this issue for the next month, as we're short on hours for this month in the maintenance

**Comment by xurxodev** [comment]
@manuelplazaspalacio @idelcano @ifoche just for the record: this issue should be refactored to move translate method to custom views in eyeseetea-sdk and assign  a translator to sdk via init method and using dependency inversion
