### ISSUE TITLE
Add condition to online/offline status detection

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2339]
On 3 situations we need to add an extra-check of the online status:
- Just before a push
- When refreshing web pages or entering them for the first time
- When performing a login

This will be done by using a new endpoint (whose details are still not provided).

**Comment by ifoche** [comment]
Ok, we have an answer about the definition of the endpoint, that should allow us to start with the development. Here it goes:

The exact endpoint might change but it will be of the form:
`[WS_url]/available/`

eg. https://apps.psi-mis.org/eRefWSProd/available/

You will be able to use the GET method.

The response to the endpoint will be:
```
{
   "available": true / false,
   "msg": "A plain text message such as: Available / In Maintenance / Unavailable"  
}
```
It is not implemented yet, but that should allow you to make progresses.

**Comment by xurxodev** [comment]
@idelcano @ifoche This issue is not finished by manu, when we have maintenance hours again we should finish it, I assign it to @idelcano

**Comment by ifoche** [comment]
Please find below the answer with the final endpoint implementation. Apparently we will need to add /api/ to the URL
```
Below api endpoint is now available:
https://apps.psi-mis.org/eRefWSProd/api/available
You can also do these:
https://apps.psi-mis.org/eRefWSProd/api/available?detail=Y
https://apps.psi-mis.org/eRefWSProd/api/available?detail=Y&timeout=1000
if 'detail=Y', possible additional information is:
- requestTime, timeoutUsed, wsSettingCacheRefreshed
'wsSettingCacheRefreshed' only shows up if 'wsSetting' cache were refreshed due to timeout or user request, thus, took a bit more time to response on this api endpoint.
```
