### ISSUE TITLE
Check alarm logic

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2340]
The client is complaining for several minutes waiting for the alarm to be launched. So he's asking for confirmation on what's the logic under the alarm. 

As far as I know, the alarm only has to do with the logic present in the onCreate() function in the BaseActivity that's calling the AlarmPushReceiver class. 

Looking at there, the push period should depend on the variable stored in the strings file
```
    <string name="PUSH_PERIOD" translatable="false">10</string>
```

But it seems like there's something else interacting with the alarm, as it's rare that a push last for only 10 seconds. 

We would need to properly analyze the push and determine how much time we spend on each task...like:
- xxx secs waiting for alarm
- xxx secs converting the vouchers
- xxx secs checking for the quarantine
- ...

We should end up with something meaningful explaining why the app's not lasting for 10 seconds on each retry

**Comment by ifoche** [comment]
The idea is that we will finish with something like a push every minute...but a real push, not like now that you have an alarm every 10 seconds and that's not really happening

**Comment by idelcano** [comment]
@ifoche  the way alarms work was changed for api >19. 
When you set a alarm with less than 1 minute, the alarm works like alarms with 1 minute.
I think the minimum period is 1 minute.

Users talking about this problem:
 https://stackoverflow.com/a/34913854
"The documentation needs to be updated. As of I think Android 5.1 
(API version 22) there is a minimum period of 1 minute for repeating alarms, and alarms cannot be set less than 5 seconds in the future."

I have checked that our alarm (with 10 seconds) runs every minute.
I tested using  120 secs and checked that it runs every 2 minutes (works as expected).

All this periods are not exact:

about <1 sec converting one voucher
about 1 sec for ONE quarantine
about 10 sec for push one voucher

about 60secs minimum(but not exact) waiting for alarm
Example:
E/PushStartAlarmT: 12/03/2018 22:06:39.064 onReceive
E/PushStartAlarmT: 12/03/2018 22:07:39.066 onReceive
E/PushStartAlarmT: 12/03/2018 22:08:34.063 onReceive
E/PushStartAlarmT: 12/03/2018 22:09:34.064 onReceive
E/PushStartAlarmT: 12/03/2018 22:10:34.064 onReceive


I did a test starting the alarm on every onReceive and it works every 10 seconds, as you can see the in this log:

E/PushStartAlarmT: 12/03/2018 22:59:11.493 setPushAlarm

E/PushStartAlarmT: 12/03/2018 22:59:21.495 onReceive
E/PushStartAlarmT: 12/03/2018 22:59:21.496 cancel
E/PushStartAlarmT: 12/03/2018 22:59:21.497 setPushAlarm

E/PushStartAlarmT: 12/03/2018 22:59:31.499 onReceive


![untitled diagram](https://user-images.githubusercontent.com/5302538/49541154-3ae97880-f8d2-11e8-841e-02454a0340c7.png)
