### ISSUE TITLE
On app start download only login activity terms

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2352]
The App is downloading languages during its boot time. This performance issue consist on downloading only login terms during boot time, enough to show the login screen and then while presenting the login screen download in background the full languages

**Comment by xurxodev** [comment]
@ifoche According to POEditor documentation It's not possible to request term list filtering by the term. Another approach that we can to use is to download from splash activity only language list and terms of current language and then in background download all languages terms. Do you think it's OK?

**Comment by ifoche** [comment]
@xurxodev you're right. Filters can only be applied to export endpoint, tdate_desc order parameter from poeditor website is not available as a date filter and there's no combination order+paging that could also do the trick so... I guess yours is the best and only solution we can have. Go ahead with that (and thank you!)
