### ISSUE TITLE
Move progress activity to a Dialog on top of Survey

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2357]
Progress Activity is loaded while Survey is being prepared. That could be moved to a Dialog on top of the Survey, just removed when the Survey is loaded

**Comment by xurxodev** [comment]
@ifoche in Connect to open survey the progress messages are never shown because only there are one tab and workflow engine build is very fast. I think this messages appear in Cambodia, CNM ...
