### ISSUE TITLE
When too much surveys in the screen, scroll is very slow

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2379]

**Comment by xurxodev** [comment]
@ifoche currently our adapter for surveys is a little complex because is the same for all apps. I think is danger refactor it now. But for me with 108 surveys the scroll work ok.
[video](https://drive.google.com/file/d/1YnTgBKeA1cGodjckdH3DbaU3UYb4HbsQ/view?usp=sharing)

**Comment by ifoche** [comment]
There's already an issue to track this refactor (#2394) so closing this issue as a duplicate of that one
