### ISSUE TITLE
After leaving the form open for some time (~5-10min) "Submit" is impossible

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2418]
To reproduce, fill a form and leave the app open for 5-10min.
When coming back to it, pressing the submit button is not possible.

**Comment by xurxodev** [comment]
@ifoche I can not reproduce this bug. I have created a new survey with different family scenarios, wait 10 minutes and click on submit and work.
I have tested on emulator and device

**Comment by ifoche** [comment]
We have more info on how to reproduce it. Actually it's when you click to submit and then go back to the survey from the summary by clicking the "x". See this video:
https://drive.google.com/file/d/1--u2afSAdy-ry_CxzNvOhBTQolRijeTP/view 

I replicated it with my phone and in my case what happens is that there's a value that is deleted from the survey and then the validation doesn't pass
