### ISSUE TITLE
When a soft login appears any survey in progress is deleted

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2424]
Can be replicated by killing the app inside a form and opening back again. The survey won't be there in the list

**Comment by xurxodev** [comment]
@ifoche The title of the issue and description is not the same case. According to the title when a soft login appear the survey in progress is deleted but this I have not reproduced. I have recorded a video where you can see that when soft login appears with the survey in progress work well. [Video](https://drive.google.com/file/d/1r02qx498r8aKZRcMaTAMI17PEhZ8vr9f/view?usp=sharing)

Other case is the description, when the app is killing while you are creating a new survey this survey is lost but the app always has worked in this way. The in-progress surveys never have appeared in the list. 

Only when an in-progress survey has been created from an external app then the survey is opened when the app starts but never will appear in the list.

**Comment by ifoche** [comment]
After talking to the client, the answer is that they will talk to the users in case they prefer the survey to appear when you create an in progress one, but the starting point will be assuming that they won't, so closing this issue and considering it as invalid
