### ISSUE TITLE
Newly submitted record not added to queue list

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/pictureapp#2434]
We have a problem reported by the Mozambique team (MZ test account: MZ_TEST_IPC / 1234).
Basically some of the newly submitted records "never make it to the queue". We captured that in a screen cast:  
https://drive.google.com/file/d/1yCxrmuJEGmaxeg4LY6aNCFLLf6GpO8dP/view?usp=sharing  
You can watch form 4:05 when the record is submitted.  
We can notice that when the screen transitions back to the dashboard, the records seems to be visible at the beginning and then seems to disappear.
Only users form MZ and that selected program = IFPP have reported this issue, but we are not 100% confident there is a connection.

**Comment by xurxodev** [comment]
@ifoche I have tested this issue again and I can not reproduce it

**Comment by ifoche** [comment]
Alpha tester report:

We are still experiencing this bug in version 1.4.4

Below is a link to a video showing the bug. Please watch from 8:00
https://drive.google.com/open?id=139cSwaXvuarkT6kus84ohQWSZ-Hiw0p1

Attached also is a copy of the local database.
[compressedData.zip](https://github.com/EyeSeeTea/EReferralsApp/files/3727683/compressedData.zip)

Device specs: Nokia 4.2 running Android 9.0 (Pie) with 3 GB RAM
