### ISSUE TITLE
Offline login feature for Lenovo Tab 4 10 TB-X304F

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2444]
We are getting reports that the offline login feature is not working for the Lenovo Tab 4 10 TB-X304F running Android version 7.1.1.

Attached is a local database from a Lenovo Tab 4 10 TB-X304F.
[compressedData.zip](https://github.com/EyeSeeTea/EReferralsApp/files/3729711/compressedData.zip)

User Code: ZW_TEST_IPC
PIN: 1234

**Comment by xurxodev** [comment]
@ifoche as we supposed, I can´t reproduce this bug. For me offline soft login is working ok, I have reviewed the exported zip by the client and the last valid credentials are in org.eyeseetea.surveillance_ref_preferences.xml.

**Comment by xurxodev** [comment]
@ifoche I have tested this issue again with new sent database and preferences, I can´t reproduce this bug. For me offline soft login is working ok, I have reviewed the exported zip by the client and the last valid credentials are in org.eyeseetea.surveillance_ref_preferences.xml also.
