### ISSUE TITLE
"defaultValue" not working if control type is FREE_TEXT

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2448]
All is in the title.
If the control type is FREE_TEXT, if a "defaultValue" is specified it does not get populated.

**Comment by xurxodev** [comment]
@ifoche if I configure a default value for FirstName question with value "test" in dataStore, the app to create a new survey show me "test" value for the first name question. I can not reproduce this bug.

**Comment by xurxodev** [comment]
@ifoche I have tested with SHORT_TEXT and LONG_TEXT and work for me.
