### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#28]
- [ ] Check push (Once  done we will merge it what makes sense into malariapp)
   - [ ] Check correct push
   - [ ] Check incorrect push (wrong uid and wrong credential)
   - [X] Check fails when no organization unit is set
   - [X] Check fails when location is not available

**Comment by ivanarrizabalaga** [comment]
@adrianq basic 'negative' samples are done, I would need some more time to fake current location in order to complete the push.

According to this link it looks easy (http://pastebin.com/Nvn1sMfX)

**Comment by ifoche** [comment]
As tests are now largely obsolete, closing this  issue that we will reopen once we will have the time for taking care about tests
