### ISSUE TITLE
Modify question-relations to workflow engine to model recursive answers

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#303]

**Comment by ifoche** [comment]
In the future workflow there will be answers that will say "Invalid". These answers will force the user to repeat the question incrementing at the same time a "repeat counter" that will display in the question. 

To model it, the question will be child of the pair "same question" - "option". This recursive relation must be detected to take the user back to the same question

**Comment by ivanarrizabalaga** [comment]
Tasks: 
 - [x] Make workflow resolves self relations
 - [ ] Inc external counter (hidden question + behaviour)
