### ISSUE TITLE
Generate initial csvs for Laos

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#309]

**Comment by ifoche** [comment]
The DEs in the server will be like in the following image:

![laos_des](https://cloud.githubusercontent.com/assets/10931645/16546600/b3dccff4-414f-11e6-88b6-4917a75a047e.png)

The options will be:
tested? 
Yes
No

Not tested reason? 
Severe malaria symtoms
Pregnant woman
Patient refused
Stock-out of RDTs

Sex?
Male
Female

RDT result?
Pf
Pv
Mix
Invalid

Treatment?
ACT 6x1
ACT 6x2
ACT 6x3
ACT 6x4
Refer patient because out of stock of ACTs
Gave patient combination of ACTs

Local infection?
Yes
No

**Comment by ifoche** [comment]
The client notify me the following:
"Just in case - Q2 "reason not tested": finally there are only 4 options: pregnant, severe, patient refused or RDT stock out.  Data element and option set are set up correctly. "

**Comment by ifoche** [comment]
DE IDs:
```
Name
LA MAL SRV - Age
Id
qQngeCbT4uI

Name
LA MAL SRV - Client telephone
Id
fnT1JoHmO94

Name
LA MAL SRV - Gender
Id
lNcuFJPKhp9

Name
LA MAL SRV - Gender
Id
lNcuFJPKhp9

Name
LA MAL SRV - Invalid RDT
Id
R53JBYOhcQM

Name
LA MAL SRV - RDT test result
Id
FPNbkUi9D55

Name
LA MAL SRV - Reason NOT tested RDT
Id
Elrozkdzh3r

Name
LA MAL SRV - Suspected case tested w/ RDT
Id
pTZpMcKg1CY

Name
LA MAL SRV - Treatment
Id
TzL693oH3D9
```

**Comment by ifoche** [comment]
Option codes:
```
Name	Code
Severe	Severe
Pregnant	Pregnant
Refused	Refused
RDT Stockout	RDT Stockout

Name	Code
Pf	Plasmodium falciparum (Pf)
Pv	Plasmodium vivax (Pv)
Mixed	Mixed
Negative	Negative

Name	Code
ACT 6x1	ACT 6x1
ACT 6x2	ACT 6x2
ACT 6x3	ACT 6x3
ACT 6x4	ACT 6x4
Referred ACT stockout	Referred ACT stockout
Combined blister	Combined blister

Name	Code
Yes	1
No	0

Name	Code
Female	F
Male	M
Unknown	U
```

**Comment by ivanarrizabalaga** [comment]
@ifoche I need to know the age thresholds for each treatment 6x1, 6x2, 6x3, 6x4.
Thanks
