### ISSUE TITLE
Find & test lao and thai fonts

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#311]

**Comment by ifoche** [comment]
They must be included only in laos variant, as well as khmer font must be only present on cambodia variant

**Comment by idelcano** [comment]
@ifoche the khmerOS font has khemer and THAI too, but not LAO

I found and tested two fonts with thai and lao languages: 
https://github.com/dejavu-fonts/dejavu-fonts 
license: http://dejavu-fonts.org/wiki/License (we need included it in our licences). 

https://fontlibrary.org/es/font/boon-v1-1  SIL Open Font License, Version 1.1.  http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web

I will use the second, but we can choose the other one.(We need include the licence in our licences text).

Note: This is to show data/metadata in thai/lao.(Questions, options, etc) only .
 
I tested the thai or lao language in emulators api 21+ and work ok too for the strings.xml.

But the strings.xml files not works in more older api s.

The thai or lao language is not supported(I can't select it in the android settings).

I tested changing the spanish values-es with the lao/thai language strings and lao/thai font: The customtextview and customeditview worked ok, but the dialogs, actionbar, settings, preferencesettings... and the android theme texts not worked.

But i think maybe it is not necessary work more in that direction, if the language is not supported by android(in old devices)...

Adrian talked about it here:
https://github.com/EyeSeeTea/malariapp/issues/822 

Is it necessary do something more?
