### ISSUE TITLE
Blank Data

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#317]

**Comment by ifoche** [comment]
We're apparently still sending blank data to the server. Please look for example to QIS_test_int OU for this month in www.psi-mis.org. This is maximum priority.

**Comment by ifoche** [comment]
To complete the information a little bit more. This is what user answered when asked about whether or not he was using GPlay version:
```
He should be. Technically he has no way to check as we've locked down settings on the phone for providers. Just in case, I've sent a request from Google Play to remotely install the latest version just now so hopefully that fixes the issue.

Panharith was able to contact the provider and had the following to say:

"On the excel that I have extracted from DHIS2 shown me that one negative case came up with blank location and time stamp for that blank location is the same to all 2902 blank data (2016-07-10 07:37:27.407). I have contacted to him this moment and he also mentioned that internet service at his outlet is working well and no application crash anyway."

Perhaps the issue is linked somehow to GPS location?
```

**Comment by ivanarrizabalaga** [comment]
@ifoche I havent really found a pattern for this behaviour yet.

I've already created a pull request to ensure only surveys with data are converted into events and I've also found a method from Crashlytics to log a caught exception.

Just as we talked there is something wrong out there this should be only be a quick fix to avoid blanks in server but not the final solution.
