### ISSUE TITLE
Prepare graphics for laos

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#333]

**Comment by idelcano** [comment]
The work is done but i find some problems with the new font:

I tested all the fonts in the android application:

The font shows Lao and Khmer texts, but thai texts do not shown.


And i can't import the images correctly using inkscape.

I tried changing some text options and program settings but  can't extract correctly all the texts, only some texts. Only adobe illustrator worked.

finally, I downloaded a 30 days trial version of adobe illustrator and i did with this for this time.
