### ISSUE TITLE
Right counter, reminder, warning layouts

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/pictureapp#343]
So far the layout of these 3 special types of questions are just a basic stuff.

All of them look pretty much the same some it should be implemented as one in DynamicTabAdapter.

**Comment by idelcano** [comment]
- [ ] Create new screen.
- [ ] Finish screens: Integer, Phone, Reminder, Alert.
- [ ] Introduce reminder before RTD question.
