### ISSUE TITLE
Modify Q5 artwork and delete (comment out) Q6

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#349]
Modify the treatment screen (Q5) artwork with [attached file](https://github.com/EyeSeeTea/pictureapp/files/397491/Q5artwork.tar.gz) and comment out Q6 question (the screen that asks whether or not the patient has traveled to a different province or country in the past two weeks). Q6 is probably gonna be deleted but for the moment commented it out.

**Comment by idelcano** [comment]
I not need remove Q6 because that question not exists in laos.

**Comment by adrianq** [comment]
PR created [here](https://github.com/EyeSeeTea/pictureapp/pull/353) I will investigate a little bit more what's going on with Q6. Let you know asap!
