### ISSUE TITLE
Change option in cambodia variant

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/pictureapp#358]
They need to be change to the following one

Plasmodium falciparum (Pf) -> Pf
Plasmodium vivax (Pv) ->  Pv

**Comment by adrianq** [comment]
@idelcano Can you make the same changes for the Laos variant?

**Comment by adrianq** [comment]
Sorry, I have checked  it and they have the right values in Laos.  I am going to merge this PR. We need to release for Cambodia. Can you please do an exhaustive testing on development (Cambodia variant)? I just wanna confirm that we haven't  broken anything with the latest changes. I will be realising probably on Monday. Thanks!
