### ISSUE TITLE
Warning and error dialog do not display properly in some devices

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#385]
![screenshot from 2016-08-13 17 54 31](https://cloud.githubusercontent.com/assets/6850223/17644897/ca72dd28-618c-11e6-80db-a27ac47c957d.png)
![screenshot from 2016-08-13 18 41 17](https://cloud.githubusercontent.com/assets/6850223/17644898/d10c3774-618c-11e6-9a89-848310db3674.png)

**Comment by adrianq** [comment]
Looks like button does not display properly or disappear from the screen. @idelcano Did you test it in a physical device as well? Btw, I tested with Android 5.0 and 5.1 and similar screen resolution they have in their current devices (700 x 1200 aprox).

**Comment by adrianq** [comment]
Another screenshot in my phisical device:
![screenshot_2016-08-13-20-03-51](https://cloud.githubusercontent.com/assets/6850223/17644770/b1975220-6187-11e6-9211-301af7334f99.png)

**Comment by adrianq** [comment]
It looks fine in the tablet. It is strongly dependent to the device resolution

**Comment by ifoche** [comment]
Fine also for me in my phone
