### ISSUE TITLE
Sometimes keyboard in age and telephone question keep blinking

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#386]
Keyboard keeps showing and hiding in a continuous loop making impossible to type anything or do any action. I have only seen this behaviour in a physical device (Android 5).

I have asked @ifoche to confirm he has a similar behaviour.  I will double check in my tablet as well.

**Comment by adrianq** [comment]
It happens as well in the tablet. Looks to me like it trying to change from one of keyboard to another one.  Maybe changing from alphanumeric to just numbers or something along these lines

**Comment by ifoche** [comment]
It stops when the answer field gets the focus. Maybe we could introduce the workaround of moving the focus to the answer field automatically...

**Comment by idelcano** [comment]
@adrianq  The problem is the getview is called two times, before show keyboard, and after show the keyboard.
Debugging the workflow is:
getview()
show keyboard with numbers.
the layout is resized
getview()
keyboard with letters.
keyboard with numbers.
I think for some reason in our device the last two steps resize the layout again and calls again the getview.

I can't replicate it in my devices, i will upload a branch with a possible solution. We can try to use 
    android:descendantFocusability="beforeDescendants"/> instead of          android:descendantFocusability="afterDescendants"

I think other solution could be create a flag to prevent the problem when the layout is re-sized and the getview is called a second time.

The second time the edittext needs be focused

I was trying other things to prevent the second getview, but not work propertly

https://github.com/EyeSeeTea/pictureapp/tree/bug-keyboard_keep_blinking

**Comment by adrianq** [comment]
@idelcano Looks like it has to do with too many wrap_content (http://stackoverflow.com/questions/2618272/custom-listview-adapter-getview-method-being-called-multiple-times-and-in-no-co) Have changed a few of them to match_parent but no succeed so far....

**Comment by adrianq** [comment]
This bit of trace is the one executed one and again:
` V/InputMethodManager: START INPUT: org.eyeseetea.malariacare.views.EditCard{263bc8f8 VFED..CL .F....ID 75,0-465,340 #7f1000be app:id/dynamic_positiveInt_edit} ic=com.android.internal.widget.EditableInputConnection@eaf6028 tba=android.view.inputmethod.EditorInfo@36e85141 controlFlags=#100
08-14 10:42:28.965 28105-28105/org.eyeseetea.surveillance_la_bb D/.DynamicTabAdapter: KEYBOARD SHOW 
08-14 10:42:28.982 28105-28105/org.eyeseetea.surveillance_la_bb D/AbsListView: onSizeChanged w=540, h=448, oldw=540, oldh=508, getChildCount=0, mSyncPosition=0, mNeedSync=false, mSyncMode=0, mAdapternull, this=android.widget.ListView{22ccc2cb V.ED.VC. ......ID 0,0-540,448 #7f1000d4 app:id/dashboard_details_list}, callstack=android.widget.ListView.onSizeChanged:1141 android.view.View.sizeChange:16020 android.view.View.setFrame:15993 android.widget.AbsListView.setFrame:2255 android.view.View.layout:15889 android.view.ViewGroup.layout:5103 android.widget.LinearLayout.setChildFrame:1954 android.widget.LinearLayout.layoutVertical:1808 android.widget.TableLayout.onLayout:448 android.view.View.layout:15900 
08-14 10:42:28.983 28105-28105/org.eyeseetea.surveillance_la_bb D/AbsListView: onSizeChanged w=540, h=448, oldw=540, oldh=508, getChildCount=1, mSyncPosition=0, mNeedSync=false, mSyncMode=1, mAdapterorg.eyeseetea.malariacare.layout.adapters.survey.DynamicTabAdapter@c1de88f, this=android.widget.ListView{1b61b016 VFED.VC. ......ID 0,0-540,448 #7f1000d0 app:id/listView}, callstack=android.widget.ListView.onSizeChanged:1141 android.view.View.sizeChange:16020 android.view.View.setFrame:15993 android.widget.AbsListView.setFrame:2255 android.view.View.layout:15889 android.view.ViewGroup.layout:5103 android.widget.RelativeLayout.onLayout:1190 android.view.View.layout:15900 android.view.ViewGroup.layout:5103 android.widget.LinearLayout.setChildFrame:1954 
08-14 10:42:28.984 28105-28105/org.eyeseetea.surveillance_la_bb V/TextView: stopSelectionActionMode()
08-14 10:42:28.990 28105-28105/org.eyeseetea.surveillance_la_bb D/ProgressBar: setMax, old = 100, new = 10, backtrace = android.widget.ProgressBar.<init>:297 android.widget.ProgressBar.<init>:259 android.widget.ProgressBar.<init>:255 java.lang.reflect.Constructor.newInstance:-2 java.lang.reflect.Constructor.newInstance:288 , this = android.widget.ProgressBar{3e639cbe V.ED.... ........ 0,0-0,0 #7f1000b6 app:id/dynamic_progress}
08-14 10:42:28.992 28105-28105/org.eyeseetea.surveillance_la_bb D/ProgressBar: setProgress, old = 0, new = 8, max = 10, backtrace = android.widget.ProgressBar.setProgress:1332 android.widget.ProgressBar.<init>:299 android.widget.ProgressBar.<init>:259 android.widget.ProgressBar.<init>:255 java.lang.reflect.Constructor.newInstance:-2 , this = android.widget.ProgressBar{3e639cbe V.ED.... ........ 0,0-0,0 #7f1000b6 app:id/dynamic_progress}
08-14 10:42:28.993 28105-28105/org.eyeseetea.surveillance_la_bb D/ProgressBar: setSecondaryProgress, old = 0, new = 0, max = 10, backtrace = android.widget.ProgressBar.<init>:301 android.widget.ProgressBar.<init>:259 android.widget.ProgressBar.<init>:255 java.lang.reflect.Constructor.newInstance:-2 java.lang.reflect.Constructor.newInstance:288 , this = android.widget.ProgressBar{3e639cbe V.ED.... ......ID 0,0-0,0 #7f1000b6 app:id/dynamic_progress}
08-14 10:42:29.084 28105-28105/org.eyeseetea.surveillance_la_bb D/ProgressBar: setMax, old = 10, new = 6, backtrace = org.eyeseetea.malariacare.layout.adapters.survey.DynamicTabAdapter.getView:401 android.widget.AbsListView.obtainView:2459 android.widget.ListView.makeAndAddView:1889 android.widget.ListView.fillSpecific:1355 android.widget.ListView.layoutChildren:1668 , this = android.widget.ProgressBar{3e639cbe V.ED.... ......ID 0,0-0,0 #7f1000b6 app:id/dynamic_progress}
08-14 10:42:29.085 28105-28105/org.eyeseetea.surveillance_la_bb D/ProgressBar: setProgress, old = 6, new = 3, max = 6, backtrace = android.widget.ProgressBar.setProgress:1332 org.eyeseetea.malariacare.layout.adapters.survey.DynamicTabAdapter.getView:402 android.widget.AbsListView.obtainView:2459 android.widget.ListView.makeAndAddView:1889 android.widget.ListView.fillSpecific:1355 , this = android.widget.ProgressBar{3e639cbe V.ED.... ......ID 0,0-0,0 #7f1000b6 app:id/dynamic_progress}
08-14 10:42:29.088 28105-28105/org.eyeseetea.surveillance_la_bb V/InputMethodManager: START INPUT: android.widget.ListView{1b61b016 VFED.VC. .F....ID 0,0-540,448 #7f1000d0 app:id/listView} ic=null tba=android.view.inputmethod.EditorInfo@c9b722a controlFlags=#100
08-14 10:42:29.090 28105-28105/org.eyeseetea.surveillance_la_bb V/TextView: stopSelectionActionMode()
08-14 10:42:29.090 28105-28105/org.eyeseetea.surveillance_la_bb V/TextView: stopSelectionActionMode()
08-14 10:42:29.090 28105-28105/org.eyeseetea.surveillance_la_bb V/TextView: stopSelectionActionMode()
08-14 10:42:29.090 28105-28105/org.eyeseetea.surveillance_la_bb V/TextView: stopSelectionActionMode()
08-14 10:42:29.090 28105-28105/org.eyeseetea.surveillance_la_bb V/TextView: stopSelectionActionMode()
08-14 10:42:29.119 28105-28105/org.eyeseetea.surveillance_la_bb V/TextView: stopSelectionActionMode()`

**Comment by adrianq** [comment]
Seem to be two list view that can be the root of all evils:
dashboard_details_list and listView

These views are probably calling getView again once the keyboard is displayed as it changes the height.

**Comment by ifoche** [comment]
@idelcano do you remember that we hid the keyboard after a question gets answered (because it was staying there even when the next question didn't need it)? Maybe that is causing a layout resize?

**Comment by ifoche** [comment]
We consider this solved as it was related to google keyboard with some android versions and client considered this not relevant to spend more time on it.
