### ISSUE TITLE
Create English release

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#399]

**Comment by idelcano** [comment]
- [x]  translate to english.
- [x] fix some text size.

@ifoche  this is the [branch](https://github.com/EyeSeeTea/pictureapp/tree/lao_english) for English release.
 Is necessary do something more than the translation?

**Comment by ifoche** [comment]
can you simply update with last version in development?

**Comment by idelcano** [comment]
@ifoche  its ready

**Comment by ifoche** [comment]
thanks!
