### ISSUE TITLE
Reminder doesn`t shown

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/pictureapp#410]
Replicate and solve it:
device:
1080 x1920
build: 10
options: age: 22, rdt: Pv

Created Tue Aug 30 2016 02:47:22 GMT+0000 (UTC) Build 10 Device type SCH-I545 Screen size 1080 Screen size 1080px by 1920px Battery 46% Unplugged Memory free 299 MB / 1807 MB

**Comment by idelcano** [comment]
@ifoche 
I think the problem should be: 
The user have installed the build 9 or lowest, with bad reminder relations. And she install the final version over that version. 
In that case the reminder is not active for the PV question because the database was not updated.. Possible solution: uninstall the app and install last version, or only delete the database.

**Comment by ifoche** [comment]
makes sense. Thanks @idelcano. For now the solution is to reinstall. Once the app will be in production, we will need to manage these changes through MigrationTable code, but as this is not yet in production, I think we can use this workaround
