### ISSUE TITLE
Move login to app start

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#443]

**Comment by ifoche** [comment]
Please note that login was also hardcoded on Laos app, so need to be taken from Login screen for Myanmar case, just like it is done in malariapp

**Comment by Strabagkantza** [comment]
I uploaded the new changes

**Comment by ifoche** [comment]
- [ ] New LoginActivity
- [ ] Modify ProgressActivity next activity for Myanmar (Dashboard instead of Settings)
- [ ] Refactor ProgressActivity (isAPull() and hashAPullAfterPush())
- [ ] On Login save user on Settings, Session and DB
- [ ] Modify EyeSeeTeaApplication in order to introduce a method for deciding the start Activity
- [ ] On user logged in, (for Myanmar) a Logout option should appear in Dashboard menu
- [ ] Introduce Logout action (wipe Survey and OrgUnit tables, remove user from Session, DB, etc)
- [ ] On server change (for Myanmar) a warning message should appear saying "hey you're about to logout and delete your data, do you want to proceed?" and on yes, call to logout and go to LoginActivity
- [ ] Remove from preferences (for Myanmar) the OU
