### ISSUE TITLE
Document workflow on pictureapp wiki

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#455]

**Comment by idelcano** [comment]
Some files to be displayed in the wiki
![diagram](https://cloud.githubusercontent.com/assets/5302538/20085437/2c6e62a2-a569-11e6-9842-703d68cf0600.png)
![workflow](https://cloud.githubusercontent.com/assets/5302538/20085444/33ea935c-a569-11e6-8770-87386bd61376.png)


[Cambodia.pdf](https://github.com/EyeSeeTea/pictureapp/files/577216/Cambodia.pdf)
[Laos.pdf](https://github.com/EyeSeeTea/pictureapp/files/577217/Laos.pdf)
![myanmarexample](https://cloud.githubusercontent.com/assets/5302538/20085530/f128b19c-a569-11e6-8cf5-4bd1b33cbe77.png)

[navigationbuilder.zip](https://github.com/EyeSeeTea/pictureapp/files/577223/navigationbuilder.zip)

**Comment by ifoche** [comment]
- [ ] Add workflow engine explanation diagram
- [ ] Add legend to diagrams

**Comment by idelcano** [comment]
https://github.com/EyeSeeTea/pictureapp/wiki/Navigation-engine
