### ISSUE TITLE
Improvements in graphics & Survey Layout

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#46]
- [x] Send mock-ups with selected and non-selected image
- [x] Modify survey look and feel
   - [x] Implement background color	
      - [x] Modify db for new field containing that color in hexadecimal
      - [x] Change layout in order to support background color	
   - [x] Modify progress bar: change numbers to Khmer and colors.
   - [x] Add darkness effect for non selected answer and remove current highlight effect (to be decided depending on mock-up feedback)
   - [x] Adapt Survey Layout for odd number of questions

**Comment by adrianq** [comment]
Mock-up already sent. Finally I sent them as screenshots. The code can be found [in this branch/commit](https://github.com/EyeSeeTea/pictureapp/commit/76c9cf93809f3009fa1171f7564b6ff92de3601d).

Waiting for client confirmation but this mainly covers the background colour support and the non-selected (darken) and selected (highlight) effect. The background colour is hardcoded at the moment.

**Comment by adrianq** [comment]
Background colour added to the db, no hardcode anymore.

**Comment by adrianq** [comment]
![screenshot from 2015-09-13 20 01 51](https://cloud.githubusercontent.com/assets/6850223/9838319/4f5a753e-5a52-11e5-9bef-d1ce46527f0f.png)

**Comment by rhardjono** [comment]
Modify progress bar: show numbers to Khmer by using strings resources and keep text colour.
