### ISSUE TITLE
Create CSVs for Myanmar

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#473]
- [x] fix multiple "root" questions bug( finally its a dbflow bug with the header.order_pos and question.order_pos)
- [x] Page 1 (Contains Q1 name, Q2 age, Q3 phone, Q4 dropdown ou, Q5 other)
- [x] Page 2 (Contains Q6 question without dataelement with three options and two questions Q7,Q8 hidden)
- [x] Page 3 swtich multiquestions (Q9,Q10,Q11)
- [x] Page 4 A question with some options. Q12. (negative-> with child question; pf,pv,mix -> with child question, invalid-> with recursive relations). 
- [x] Page 5 Q13    Negative child
- [x] Page 6 Q14   Counter
- [x] Page 7 Q15 pf,pv,mix child order 1. Options: give medication or stock.
- [x] Page 8 Q16 pf,pv,mix child order 2, Multiquestion(Q15, Q16 that is parent of Q17) 

About Q2:
The Q2 (male,female,pregnant) was implemented with:
Q1: type: No data element
- Options
  
  -O1 Male
  
  -O2 Female
  
  -O3 Female Pregnant

Q2: type: hidden
- Options
  
  -O4 Female
  
  -O5 Male

Q3 type: hidden
- Options
  
  -O6 No pregnant
  
  -O7 Pregnant

And two matches:

Q1 and O1(Male)                            matches with Q2 O5(hidden male ) 
ELSE Q2 is O4(hidden female)

Q1 and O3(Femalepregnant) matches with Q3 O7(hidden fpregnant) 
ELSE Q3 is O6(no pregnant) 

The Q3 switch has Yes - No options in the design position, but the swicth options are "false"-"true", No is selected by default ( it is true for the switch component). 
I added a logic by position( we can choice if use the "true/false" option code, or if not exist true/false option codes by the option position in csv. If the code is not "true/false" we use the answer.getOption.get(0)=false answer.getOption.get(1)=true) .

Q14 Added a "temporal logic" to limit the counter question using the Option Factor.( this solves other problem with the counter without next question too)
- [x] Bug - Parents from other headers
- [x] Bug - layout bug with view component in  multi_question_tab_switch_row.xml ( only if show/hide a question  in portrait position...)
- [x] Bug - review Q3 save new values( female - pregnant, female no pregnant, etc).
  (edited by idelcano)

**Comment by ifoche** [comment]
@idelcano I received a notification today saying this:
Ignacio: we've changed the UID for RDT DE (FfsqctsJo2s)
New optionSet is MCSMM - RDT Result (tx) - id: URYijWBvta2

Just for the record, so we can remind it later

**Comment by idelcano** [comment]
To remember in the future: 
Questions:
About switch:
1 - How know the default value in a switch button( maybe two kind of switch buttons).
2 - Remove the true/false logic and use the position logic?
About Q treatment:
1 - Can we convert it in multiquestion tab and create a imageClicakble row question? It can be 3 options, 1- button 1, 2 button 2, 3 the label question option.
About Q Invalid limit.
1- I used temporally the factor field. We need think how can save the limit.

ToDo:
1- modify the layouts to be like the client design.
2- decide if changes the switch logic(who is the default, where.. left/right)
3- End treatment questions( it is only a question with two options). And the next one is a question with 4 labelquestions.
4- Decide how save the invalid test limit.
5- Add the next/previous buttons.
