### ISSUE TITLE
Add dropdown to Login Screen to select the amount of data to be downloaded

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#482]

**Comment by ifoche** [comment]
Login Screen must present a dropdown saying "Download [no data|last 6 days | last 6 weeks | last 6 months]" with "no data" by default, and this should modify the variable that establishes the period used to download the data.

**Comment by ifoche** [comment]
@idelcano please wait before starting this task. Client told us not to implement it yet until he has authorization.

**Comment by idelcano** [comment]
I needed copy from sdk the activity_login  in our project and change some height sizes to add a new dropdown. I tried other things but not work properly (for example inject the new dropdown, but the activity_login has a heights limited by pixel dp).
