### ISSUE TITLE
Modify art logo with new pictures

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#52]
- [x] Add new logo
- [x] Modify db 
- [x] Add new images
- [x] Update background colour

**Comment by rhardjono** [comment]
An example of the new images for Sex Question:
![Uploading rdt_yes.png…]()
![Uploading rdt_no.png…]()
![Uploading rdt_cancel.png…]()

And the new logo...
![Uploading logo.png…]()
