### ISSUE TITLE
Update tabs layouts and include common header

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#550]
Currently both lists say "Unsent Data". We need sent data to say "Sent Data" in its header and review their aspect to look like the design

**Comment by idelcano** [comment]
- [ ] Change stock text.
- [ ] Create common header.
- [ ] Create webview interface for monitoring and stock fragment
- [ ]  Update dot line
- [ ] Create footer line in unsent
- [ ] Removes actual monitoring  header and move "last 6 months" select
