### ISSUE TITLE
DB not deleted on App uninstall for Android 6.0

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/pictureapp#563]
test and fix a problem skipping the logging after reinstall from 0in a mobile(related with the permissions?)

**Comment by idelcano** [comment]
@ifoche 
The problem was the next one:
In my mobile(not rooted samsung Android 6.0.1) if you deletes the application, the database is not removed.  ? 
Is a normal workflow of android app manager?
I never seen it before, is it my fault?.

Only when I removed the "app data" in adjust before reinstall, the app works correctly. 

Else the user already exist and the login screen is skipped. 

I don't sure if the problem is only with my mobile, with the android version, or with the intrusive telephone company apps... 


(The app works correctly in the first install too).

**Comment by ifoche** [comment]
ok. Thanks @idelcano. We'll move back this to backlog then, to determine if we can provide a solution for this in the future, but for now we're not addressing it, as it's not critical
