### ISSUE TITLE
Change reminders/warnings for Myanmar variant

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#564]
Myanmar has a different look&feel for Warnings/Reminders. This task will imply:
- [ ] Move confirmation button to right arrow (End test) only for Myanmar
- [ ] Allow Warning questions to represent list of label options (either by redirecting to a multiquestion labels tab either by implementing the label options on Warning)

**Comment by idelcano** [comment]
example of setText in buttons [here](https://github.com/EyeSeeTea/pictureapp/pull/567/commits/2d73f4c60e05a5900e832e26faa2bae46b6a3c76)
