### ISSUE TITLE
Polish last issues

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#591]

**Comment by ifoche** [comment]
- [ ] Make progress bar appear at the beginning (either introducing a new Splash Screen Activity either making the current work without spending so much time without progress activity)
- [ ] Show mandatory questions red asterisks also when question statement takes two lines
- [ ] Make phone validation work again
- [ ] Make survey completion to be recognized again (introducing parent-child questions and mandatory in the query that distinguish a completed survey from a not completed one)

**Comment by idelcano** [comment]
Make progress bar appear at the beginning (either introducing a new Splash Screen Activity either making the current work without spending so much time without progress activity)->fixed [here #581](https://github.com/EyeSeeTea/pictureapp/pull/581)
 Show mandatory questions red asterisks also when question statement takes two lines -> fixed [here #584](https://github.com/EyeSeeTea/pictureapp/pull/584)
