### ISSUE TITLE
Cancel should work as the negative button

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#60]
Store an X ( this value needs to be confirmed by the client) and end the survey

**Comment by rhardjono** [comment]
have to show the confirmation dialog too?

**Comment by adrianq** [comment]
Yes, same behaviour as the No option

**Comment by adrianq** [comment]
@rhardjono can you make sure we show this option as X (code) in the dashboard? The name should be 'Not tested'

**Comment by rhardjono** [comment]
Ok, i'll make this change.
