### ISSUE TITLE
Lao migrate new relation

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/pictureapp#614]
A child-parent relation between the counter invalid question was missing and was introduced in the csv. Only is needed update matches/questionrelation/questionoption tables in a migration

**Comment by ifoche** [comment]
@idelcano I think you told me today this was not going to be a problem anymore, but this task would be just to test it

**Comment by idelcano** [comment]
@ifoche  yes, is necessary update the new match/questionrelation/questionoption relation in lao,   but is not necessary add a new compulsory value update.
