### ISSUE TITLE
GPS modification

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#62]
- [x] Store GPS location when survey starts
- [x] If no location is found store ones by default (This location will be provided by the client)

**Comment by adrianq** [comment]
Default location is [GPS [10, 103]](https://www.google.co.uk/maps/place/10%C2%B000'00.0%22N+103%C2%B000'00.0%22E/@9.999239,103,9z/data=!3m1!4b1!4m2!3m1!1s0x0:0x0)

**Comment by adrianq** [comment]
https://github.com/EyeSeeTea/malariapp/commit/48c51b92a8b43ab629aefec6cd38bf45d096211d

**Comment by rhardjono** [comment]
Does the default GPS location has to be fixed in code? or configured on dimen /strings xml files. Notice that the latter one requires a convertion from String to Double.
Although you can define  in dimen.xml double values directly ...

**Comment by adrianq** [comment]
@rhardjono I would add it to the dimen/strings xml files. Although it would require some type conversion is much more maintainable
