### ISSUE TITLE
Text field improvements

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#63]
- [x] Keyboard is still displayed after completing the age field and phone field
- [x] Numeric keypad automatically display when moving to these questions
- [x] Set the input field background color to light grey

**Comment by ifoche** [comment]
[These are the lines](https://github.com/EyeSeeTea/malariapp/blob/v1.1/app/src/main/java/org/eyeseetea/malariacare/SurveyActivity.java#L519-521) where this is done in malariapp

**Comment by adrianq** [comment]
Many thanks @ifoche!

**Comment by rhardjono** [comment]
do you mean keyboard has to hide after press enter button...?

**Comment by ifoche** [comment]
In malariapp, keyboard is hidden when focus is lost. I don't know if you
want that in malariapp but I just wanted to clarify that. For me, that
makes sense

**Comment by rhardjono** [comment]
@ifoche thanks!
