### ISSUE TITLE
internationalisation broken on settings

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#645]

**Comment by ifoche** [comment]
All the settings strings that were previously translated on a language settings are not translated anymore, and likewise for the lists headers

**Comment by ifoche** [comment]
![bug-no_translations](https://cloud.githubusercontent.com/assets/10931645/21212214/c5a2a4ea-c28a-11e6-86f6-a00ec1f09a24.png)
![bug-no_translations2](https://cloud.githubusercontent.com/assets/10931645/21212218/d2405026-c28a-11e6-8df8-6d8dfb002149.png)
![bug-no_translations3](https://cloud.githubusercontent.com/assets/10931645/21212217/cd584bae-c28a-11e6-9995-567f66e9a9f3.png)

**Comment by idelcano** [comment]
The app translation is working for me in a api 23

**Comment by ifoche** [comment]
c21d8c7974d15115d4178947c83068fe20cca4d8

**Comment by ifoche** [comment]
I've rechecked with the exact commit I copied in my last comment and it looks like it's working, so let's forget about this issue
