### ISSUE TITLE
Change user/pw for the one provided by the client

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#66]
and the server if needed

**Comment by adrianq** [comment]
@josemp10 once you have created user/pw for the three environments (malariacare, dev, prod), please send me an email with the credential

**Comment by josemp10** [comment]
Work on this today

**Comment by adrianq** [comment]
@josemp10 great! please remember to associate the user to a test OU (KH_Test I believe you said) so we can test it. I guess this will require to migrate the set up for the program...

**Comment by josemp10** [comment]
I have created the user KHMCS/KHMCSadmin1 in malariacare and in dev. Can
you test it? It may require some adjustments...

Moving the things to production it is going to take a while (Thursday or
Friday)

**Comment by adrianq** [comment]
@idelcano can you please test in detail the app for dev and malariacare and report any issue?

@josemp10 Thanks! this release should be close by Friday. It would be good if we can have it asap so we can have some time to test it.

**Comment by idelcano** [comment]
@josemp10 
I can get the list of org units with that user, but i can´t save surveys.
The user dont have permission to access to the program.


 Response in dev.psi-mis.org and in malariacare.psi.org:
 {"httpStatus":"OK","httpStatusCode":200,"status":"OK","message":"Import was successful.","response":{"responseType":"ImportSummaries","imported":0,"updated":0,"ignored":0,"importSummaries":[{"responseType":"ImportSummary","status":"ERROR","description":"Current user does not have permission to access this program","importCount":{"imported":0,"updated":0,"ignored":0,"deleted":0}}]}}

**Comment by josemp10** [comment]
Ok, @idelcano, will work on this later today and will test it by myself.
The code in the android app is ok, it is a matter of DHIS2 configuration.
Will let you know once it is donde.

**Comment by josemp10** [comment]
guys... I will arrive at the hotel in about 3 hours yet. In the meantime,
and if you have time, can you test it again one more time in dev (ONLY in
dev)? (I have made some changes in the server). If you have time to do
that, please let me know the results.

**Comment by idelcano** [comment]
No problem , I'll try it on the test server.

**Comment by idelcano** [comment]
it´s working, 
i test in dev.psi-mis.org in the org_unit: KH_TEST 
Example of positive survey: https://dev.psi-mis.org/api/events/iW00i4uifBB
Example of negative survey: https://dev.psi-mis.org/api/events/CvUeilEtxWS
Example of closedData: https://dev.psi-mis.org/api/organisationUnits.json?paging=false&fields=id,closedDate&filter=code:eq:KHTest&filter:programs:id:eq:IrppF3qERB7

In events capture looks all right.
Should I test the process in other organizations ?
I will send one survey in all of the others active org_units

**Comment by josemp10** [comment]
You can try with the following org. units:

KH Outlet 1-1
KH Outlet 1-2
KH Outlet 1-3
KH Outlet 1-4
KH Outlet 1-5

KH Outlet 2-1
KH Outlet 2-2
KH Outlet 2-3
KH Outlet 2-4
KH Outlet 2-5

It should work for all of them.

Thanks @idelcano for testing this.

**Comment by adrianq** [comment]
Great! Good job guys! @josemp10 let us know when you are done moving the set-up to production so we can test the app. This is practically the last task left in this release.

**Comment by idelcano** [comment]
Should I test the entire process for each one ?

I tested the entire process in one, and in the others org units, i sent some diferent surveys  and i checked the values.

**Comment by josemp10** [comment]
Nono.... just one or two of them....
