### ISSUE TITLE
Repeat 2.25 sdk process from malariapp

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#681]
Create a feature-new_sdk branch and make it work with 2.25-EyeSeeTea sdk branch just like in malariapp repository

**Comment by idelcano** [comment]
[picture branch](https://github.com/EyeSeeTea/pictureapp/tree/feature-new_sdk )

Some bugs:
Login button is not working.
Crash on new survey ( wrong queries?)
crash on logout.
