### ISSUE TITLE
Investigate autocomplete textfield

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#77]

**Comment by idelcano** [comment]
Look at [this](http://developer.android.com/reference/android/widget/AutoCompleteTextView.html)

**Comment by idelcano** [comment]
I created the branch with the implementation of autocomplete in the Organitation Unit settings. The method for get the array of Strings is pending for know the call to the server

**Comment by idelcano** [comment]
Only two organitation units have code value [link](https://malariacare.psi.org/api/programs/IrppF3qERB7)
