### ISSUE TITLE
Parse push response for dhis 2.20

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#82]
This was already done for Malariapp [here](https://github.com/EyeSeeTea/malariapp/issues/462).

[This PR](https://github.com/EyeSeeTea/malariapp/pull/464) does the trick

**Comment by adrianq** [comment]
@idelcano again we will talk about this on Monday

**Comment by idelcano** [comment]
[commit](https://github.com/EyeSeeTea/pictureapp/commit/547e2e43ad4f9c75ff5e2ac12299d72bb5593432)
