### ISSUE TITLE
Extract imei, serial and telephone number

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/pictureapp#83]
@idelcano I am creating the issue about the things we talked on Friday.  Note that  there are three things we would require from the user (last day we talked about two of them). Please, create a branch but do not open the PR, there will be more work on this side

**Comment by idelcano** [comment]
The activity is null in PushClient, i can´t send the activity from a IntentService(pushService), and it is required for extract the phone metadatas. 

I tried different ways and read a lot of things. Finally, i create 3 methods setter in pushClient for the phone metadata. And i set the phone metadata from PushService.

I look   
"//FIXME This should change for a sharedpreferences url that is selected from the login screen" 
And i fix it too(5 minutes). ( I suppose is the same url server of  the url server saved in Settigns sharedpreferences)

**Comment by adrianq** [comment]
@ifoche Maybe you can shed some light on this... We need to get the imei,serial and telephone number and we would like to do this only once  (every time we execute the app). This data should be accessed for the push client. Where do you think  it is a good place?

**Comment by ifoche** [comment]
A good place for the acquisition may be, as you're migrating to DBFlow, the Application class. When you migrate to DBFlow you need to extend Application class in order to make the FlowManager.init() and FlowManager.destroy(), and in our case we use that class extension also to override a function that allows us to use MultiDex (and so, to integrate the SDK). In Malaria, we use that class also to introduce Crashlytics, to init preferences and init the GPS location memory. Wouldn't that be a good place for this? Of course, it is not needed to migrate to DBFlow to extend the class, but it is a must when you do :)

**Comment by ifoche** [comment]
I'm talking about [this](https://github.com/EyeSeeTea/malariapp/blob/master/app/src/main/java/org/eyeseetea/malariacare/EyeSeeTeaApplication.java) (just in case)

**Comment by adrianq** [comment]
Great! We were thinking about adding it there.  So definitively we are on the same page :) btw, shall we store it in the preferences? what do u think? @idelcano was having some problems accesing the preferences from the PushClient.

**Comment by ifoche** [comment]
Regarding that, I'm not really sure. Is it something user will be allowed to change himself? Every tutorial I read about preferences advised that preferences are not variables to store. If the user is not having the opportunity for changing it, maybe this is something that the Session class can store, don't you think? However, several people use preferences as a storage point, we can do it, but I think this is more something related to "good practices" not doing it.

**Comment by adrianq** [comment]
Yes, session sounds as the right place for this. @idelcano Can we store these in the session? Once we migrate the ORM to dbflow we can extrart the information in the EyeSeeTea application class as @ifoche suggested.

**Comment by idelcano** [comment]
I think is the best way, I did it and works.

**Comment by adrianq** [comment]
Great! Many thanks @ifoche for the advice and @idelcano for the implementation!
@josemp10 do we need to have uids for these new fields, right? Can you create them for us?

**Comment by idelcano** [comment]
@adrianq i think you dont told me the method and keys for save the phonemetadata values (i ask you something and we forgot it, sorry).

**Comment by josemp10** [comment]
Yep, will create the uids by tomorrow...

**Comment by adrianq** [comment]
@josemp10 If you can create these uids for dev (and maybe prod) as well it would be great

**Comment by josemp10** [comment]
Yep. The uid code for these dataelements will be the same in all machines.

**Comment by josemp10** [comment]
Done.

Telephone number: UkGuMlmNtJH
IMEI: RuNZUhiAmlv
Serial number: zZ1LFI0FplS

They have not been created in dev yet, but they will have the same uid.

**Comment by idelcano** [comment]
Done (thanks to all). 
Only have a problem with the  phone number field.   
There are Some SIM Cards/Operators out there who don´t provide the phone numbers. [link](http://i.stack.imgur.com/Ta2Xl.png) 
I test in my samsung s4-vodafone and  i can´t get the phone number.
