### ISSUE TITLE
Restringe acces for a org_unit with more than 30 surveys in one hour

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/pictureapp#87]

**Comment by idelcano** [comment]
I need check it:
Call to the program in the server, where id is the org_unit [link](https://malariacare.psi.org/api/organisationUnits/Pg91OgEIKIm.json?fields=id,name,openingDate,closedDate)
And this return the closedDate of the organisationUnits [link](https://malariacare.psi.org/api/organisationUnits/Pg91OgEIKIm/closedDate)

**Comment by idelcano** [comment]
Hi @adrianq i have two problems with this issue.

The "valid" organization units(with value "code") not have closedDate
Only two organitation units have code value [link](https://malariacare.psi.org/api/programs/IrppF3qERB7) and neither had a closeddate 
This not had code value, but had closedDate value [link](https://malariacare.psi.org/api/organisationUnits/u5jlxuod8xQ/closedDate)
This had a code value, but not had closedDate [link](https://malariacare.psi.org/api/organisationUnits/Pg91OgEIKIm/closedDate)

Anyway, i have other problem. Im not sure how save the date of the sent surveys. 
In the aplication have a button for remove all surveys. 
I think the best way is ask to the server the date of the 30(order by date descending) survey and compare with the actual date, it is possible?

**Comment by adrianq** [comment]
@idelcano can you just set the closedDate for the one that has a code? Maybe you can set the closedDate with the api url I sent you (PATCH method) and then check it, right? Just give it a try, if this is not possible I would ask @josemp10  to update the content server side.

Regarding your second question, [this url](https://malariacare.psi.org/api/events.json?program=IrppF3qERB7&orgUnit=u5jlxuod8xQ&startDate=2015-07-20T04:00:00.000) should do the trick. Substitute program,orgUnit and startDate for the proper values @josemp10 is there a better way to do this query? Something more efficient maybe?
