### ISSUE TITLE
When insert inputs that has not treatment matrix as age 5 or 0 and pregnant when navigate to treatment question is empty

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/pictureapp#901]

**Comment by ifoche** [comment]
In the event that there's no treatment associated to the selected combination of entries, create a label question on-the-fly for the dynamic treatment question saying:
"There's not treatment for this combination of entries. Please talk to the administrator".

That will make users to double-check their selections, avoiding impossible cases like "female age 3 pregnant"
