### ISSUE TITLE
Font size and rotation bugs

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#936]

**Comment by ifoche** [comment]
- [ ] Font size extra small & small doesn't make sense. They must be removed
- [ ] When you select large font size, you put the phone landscape, click on a question to make the keyboard appear and then rotate the phone...the app crahses
- [ ] In general, when the app is not in default font size, the app crashes from time to time.

**Comment by idelcano** [comment]
-  Font size extra small & small doesn't make sense. They must be removed
Solved in:
https://github.com/EyeSeeTea/pictureapp/pull/939
- In general, when the app is not in default font size, the app crashes from time to time.
Try to be fixed in:
https://github.com/EyeSeeTea/pictureapp/pull/940
