### ISSUE TITLE
New option in Reason for referral

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#986]
Take a look to [the mockup](https://drive.google.com/open?id=0B8KIRhh6kcl6TjcxdDFTMFlqYnM)

**Comment by idelcano** [comment]
The screen with the new option:
![device-2017-03-27-103006](https://cloud.githubusercontent.com/assets/5302538/24347501/d18d5752-12d8-11e7-920f-0e2a51fb1c70.png)
The option text is in the png like the others for this question.
